import os
from dotenv import load_dotenv
import ccxt

load_dotenv()

bybit = ccxt.bybit(
    {
        "options": {
            "defaultType": "future",
        },
        "timeout": 30000,
        "apiKey": os.getenv("bybit_pub"),
        "secret": os.getenv("bybit_sec"),
        "enableRateLimit": False,
    }
)


binance_ticker_list = [
    "SUSHIUSDT",
    "INJUSDT",
    "ORDIUSDT",
    "ONGUSDT",
    "MASKUSDT",
    "KASUSDT",
    "ACEUSDT",
    "MEMEUSDT",
    "BCHUSDT",
    "TRXUSDT",
    "DEFIUSDT",
    "KSMUSDT",
    "BIGTIMEUSDT",
    "XRPUSDT",
    "RDNTUSDT",
    "SUIUSDT",
    "ZENUSDT",
    "BTCUSDT",
    "ALPHAUSDT",
    "MINAUSDT",
    "1000RATSUSDT",
    "BSVUSDT",
    "SSVUSDT",
    "CHZUSDT",
    "STORJUSDT",
    "BTCDOMUSDT",
    "QTUMUSDT",
    "FETUSDT",
    "ONTUSDT",
    "1000XECUSDT",
    "AIUSDT",
    "HIGHUSDT",
    "LEVERUSDT",
    "ETCUSDT",
    "APTUSDT",
    "CAKEUSDT",
    "GALAUSDT",
    "TUSDT",
    "DOGEUSDT",
    "IOTXUSDT",
    "DASHUSDT",
    "ALICEUSDT",
    "TIAUSDT",
    "WLDUSDT",
    "XTZUSDT",
    "JTOUSDT",
    "COMBOUSDT",
    "RVNUSDT",
    "CFXUSDT",
    "CYBERUSDT",
    "BADGERUSDT",
    "WOOUSDT",
    "LRCUSDT",
    "ANKRUSDT",
    "CKBUSDT",
    "ASTRUSDT",
    "STXUSDT",
    "SOLUSDT",
    "GMXUSDT",
    "FLMUSDT",
    "JOEUSDT",
    "TWTUSDT",
    "ONEUSDT",
    "ATOMUSDT",
    "LTCUSDT",
    "RIFUSDT",
    "NMRUSDT",
    "1000LUNCUSDT",
    "CRVUSDT",
    "AXSUSDT",
    "EGLDUSDT",
    "NFPUSDT",
    "NEOUSDT",
    "LINKUSDT",
    "LQTYUSDT",
    "DENTUSDT",
    "SNXUSDT",
    "ARKMUSDT",
    "EDUUSDT",
    "YGGUSDT",
    "ALGOUSDT",
    "POWRUSDT",
    "IOTAUSDT",
    "SUPERUSDT",
    "SXPUSDT",
    "XLMUSDT",
    "ZRXUSDT",
    "UMAUSDT",
    "USDCUSDT",
    "STGUSDT",
    "CHRUSDT",
    "KAVAUSDT",
    "FXSUSDT",
    "STEEMUSDT",
    "AAVEUSDT",
    "LINAUSDT",
    "OPUSDT",
    "MAGICUSDT",
    "COMPUSDT",
    "BALUSDT",
    "MAVUSDT",
    "TLMUSDT",
    "1000PEPEUSDT",
    "VETUSDT",
    "QNTUSDT",
    "ZECUSDT",
    "APEUSDT",
    "BEAMXUSDT",
    "AUCTIONUSDT",
    "FLOWUSDT",
    "ETHUSDT",
    "ARKUSDT",
    "GRTUSDT",
    "RUNEUSDT",
    "ILVUSDT",
    "BLURUSDT",
    "COTIUSDT",
    "ENJUSDT",
    "DYDXUSDT",
    "BAKEUSDT",
    "ARUSDT",
    "ICPUSDT",
    "SKLUSDT",
    "SEIUSDT",
    "OGNUSDT",
    "BELUSDT",
    "LDOUSDT",
    "XVSUSDT",
    "ROSEUSDT",
    "DUSKUSDT",
    "HIFIUSDT",
    "UNIUSDT",
    "OXTUSDT",
    "PERPUSDT",
    "MKRUSDT",
    "MOVRUSDT",
    "MANAUSDT",
    "CELOUSDT",
    "ZILUSDT",
    "FILUSDT",
    "ATAUSDT",
    "C98USDT",
    "BNTUSDT",
    "TRBUSDT",
    "ETHWUSDT",
    "POLYXUSDT",
    "ARPAUSDT",
    "1000SHIBUSDT",
    "1INCHUSDT",
    "BNBUSDT",
    "HOOKUSDT",
    "XVGUSDT",
    "JASMYUSDT",
    "NEARUSDT",
    "KNCUSDT",
    "IDUSDT",
    "HOTUSDT",
    "SANDUSDT",
    "BATUSDT",
    "EOSUSDT",
    "NKNUSDT",
    "ICXUSDT",
    "RSRUSDT",
    "PEOPLEUSDT",
    "1000FLOKIUSDT",
    "YFIUSDT",
    "XMRUSDT",
    "PHBUSDT",
    "BANDUSDT",
    "HFTUSDT",
    "GMTUSDT",
    "API3USDT",
    "CTSIUSDT",
    "XAIUSDT",
    "SPELLUSDT",
    "NTRNUSDT",
    "ACHUSDT",
    "WAXPUSDT",
    "SFPUSDT",
    "LUNA2USDT",
    "THETAUSDT",
    "ARBUSDT",
    "AGLDUSDT",
    "PYTHUSDT",
    "1000BONKUSDT",
    "GASUSDT",
    "IMXUSDT",
    "TOKENUSDT",
    "USTCUSDT",
    "BNXUSDT",
    "DODOXUSDT",
    "DOTUSDT",
    "ENSUSDT",
    "RLCUSDT",
    "PENDLEUSDT",
    "ADAUSDT",
    "1000SATSUSDT",
    "HBARUSDT",
    "MTLUSDT",
    "GTCUSDT",
    "BICOUSDT",
    "LPTUSDT",
    "IOSTUSDT",
    "AVAXUSDT",
    "TRUUSDT",
    "CELRUSDT",
]


def get_tickers_bybit() -> list[str]:
    result = list(bybit.fetch_tickers().keys())
    result = [x.replace("/USDT:", "") for x in result if "/USDT:USDT" in x]
    return result


bybit_ticker_list = get_tickers_bybit()


result = list(set(bybit_ticker_list) & set(binance_ticker_list))

print(result)
print(len(result))
