import ccxt
import time
import pandas as pd
import os
import telegram
import datetime
from pprint import pprint


def get_tickers(base):
    # base = '/USDT' or '/BNB' or '/BTC' or ...
    All_ticker = binance.fetch_tickers().keys()
    tickers = [s for s in All_ticker if base in s]
    result = []
    for i, item in enumerate(tickers):
        ohlcv = binance.fetch_order_book(item)
        if len(ohlcv["bids"]) != 0:
            result.append(item)
    return result


binance = ccxt.binance(
    {
        "apiKey": "3pFJ5lblk8ff8brlz2plOG2o",
        "secret": "KKFk0a-YvtW8aEcS33HbQlxJ63rHpdA95D7IWNALSOTVraB1",
        "enableRateLimit": True,
        "RateLimit": 10000,
    }
)
binance.load_markets()


time_frame = "1d"


# ticker_list = list(set(get_tickers('/ETH')) | set(get_tickers('/BNB')) | set(get_tickers('/USDT')) | set(get_tickers('/BTC')))

# ticker_list = ['WTC/BNB', 'GTO/ETH', 'FTM/BNB', 'THETA/ETH', 'XLM/BNB', 'WIN/USDT', 'ATOM/USDT', 'NULS/USDT', 'XZC/ETH', 'HC/USDT', 'KEY/ETH', 'IOTA/ETH', 'ZEC/ETH', 'ADA/ETH', 'ZEN/ETH', 'POWR/ETH', 'LOOM/ETH', 'TROY/USDT', 'MFT/ETH', 'ZIL/USDT', 'TOMO/BNB', 'BNB/ETH', 'ICX/USDT', 'XRP/USDT', 'DOCK/USDT', 'BTCUP/USDT', 'BQX/ETH', 'ETC/ETH', 'WAVES/ETH', 'NPXS/ETH', 'HOT/ETH', 'LEND/USDT', 'HOT/USDT', 'ZRX/BNB', 'WAN/ETH', 'ALGO/BNB', 'WRX/BNB', 'MDT/USDT', 'ADA/USDT', 'NULS/ETH', 'BLZ/ETH', 'XMR/ETH', 'COS/BNB', 'IQ/BNB', 'PERL/BNB', 'NPXS/USDT', 'MCO/USDT', 'OMG/USDT', 'FET/USDT', 'LEND/ETH', 'EUR/USDT', 'LTC/ETH', 'WAVES/USDT', 'ICX/BNB', 'NKN/USDT', 'ZEC/BNB', 'KEY/USDT', 'LRC/ETH', 'LSK/ETH', 'WIN/BNB', 'PERL/USDT', 'ZIL/ETH', 'MANA/ETH', 'NEO/BNB', 'XTZ/BNB', 'FUN/USDT', 'THETA/BNB', 'BNT/ETH', 'GNT/ETH', 'TROY/BNB', 'WTC/USDT', 'MBL/BNB', 'STEEM/ETH', 'RLC/ETH', 'AION/ETH', 'DOCK/ETH', 'CHZ/BNB', 'CELR/BNB', 'STX/BNB', 'LRC/USDT', 'XRP/ETH', 'MITH/BNB', 'BTS/USDT', 'PAX/USDT', 'BTT/USDT', 'ARPA/USDT', 'BAT/ETH', 'CTXC/USDT', 'BTCDOWN/USDT', 'OST/ETH', 'DATA/USDT', 'HIVE/BNB', 'KAVA/BNB', 'MCO/ETH', 'GTO/USDT', 'ETC/BNB', 'KAVA/USDT', 'RLC/USDT', 'NANO/USDT', 'ELF/ETH', 'MFT/USDT', 'CTSI/USDT', 'FTT/USDT', 'SNT/ETH', 'KNC/ETH', 'MBL/USDT', 'ZRX/USDT', 'XTZ/USDT', 'BRD/BNB', 'QKC/ETH', 'DUSK/USDT', 'EOS/BNB', 'STMX/BNB', 'HBAR/USDT', 'GXS/ETH', 'NEO/ETH', 'QSP/ETH', 'ADX/ETH', 'MFT/BNB', 'MATIC/BNB', 'NEBL/BNB', 'REN/USDT', 'ARDR/USDT', 'VITE/USDT', 'XEM/ETH', 'MDT/BNB', 'ANKR/BNB', 'HIVE/USDT', 'BTT/BNB', 'ONT/ETH', 'IOTX/ETH', 'VET/ETH', 'ICX/ETH', 'ARPA/BNB', 'DREP/USDT', 'REP/ETH', 'ZEN/BNB', 'TUSD/USDT', 'IOST/ETH', 'USDC/USDT', 'EOS/USDT', 'LSK/USDT', 'ONT/USDT', 'XZC/USDT', 'OGN/BNB', 'LINK/USDT', 'DASH/ETH', 'ARN/ETH', 'SC/BNB', 'CTSI/BNB', 'ETC/USDT', 'BAT/USDT', 'SOL/BNB', 'ENJ/BNB', 'LTC/USDT', 'REP/USDT', 'ONE/BNB', 'CHR/BNB', 'BUSD/USDT', 'MITH/USDT', 'STORJ/ETH', 'OGN/USDT', 'STMX/ETH', 'XMR/BNB', 'TRX/USDT', 'XLM/USDT', 'ADA/BNB', 'COTI/BNB', 'HBAR/BNB', 'BLZ/BNB', 'ENJ/USDT', 'FUN/ETH', 'NAS/ETH', 'ONE/USDT', 'BAT/BNB', 'CELR/USDT', 'ZIL/BNB', 'KNC/USDT', 'BNB/USDT', 'TOMO/USDT', 'ETH/USDT', 'MATIC/USDT', 'FTM/USDT', 'HOT/BNB', 'IOTA/USDT', 'COTI/USDT', 'CMT/ETH', 'BAND/BNB', 'DOGE/USDT', 'AE/ETH', 'NCASH/ETH', 'STMX/USDT', 'GXS/USDT', 'COS/USDT', 'VIB/ETH', 'ERD/BNB', 'BCH/BNB', 'BNT/USDT', 'DASH/USDT', 'QLC/ETH', 'BEAM/USDT', 'EVX/ETH', 'VET/BNB', 'NKN/BNB', 'WAN/USDT', 'ANKR/USDT', 'OMG/ETH', 'STX/USDT', 'BAND/USDT', 'NANO/ETH', 'ENG/ETH', 'TNT/ETH', 'ALGO/USDT', 'DENT/USDT', 'TCT/USDT', 'THETA/USDT', 'NEO/USDT', 'LINK/ETH', 'NEBL/ETH', 'WABI/BNB', 'LTC/BNB', 'TFUEL/USDT', 'ZEC/USDT', 'KMD/ETH', 'RLC/BNB', 'FET/BNB', 'WAVES/BNB', 'AION/BNB', 'IOST/USDT', 'RVN/USDT', 'CHR/USDT', 'ENJ/ETH', 'BTC/USDT', 'IOTX/USDT', 'AION/USDT', 'CDT/ETH', 'CVC/ETH', 'MTL/ETH', 'COCOS/USDT', 'COCOS/BNB', 'XZC/BNB', 'XRP/BNB', 'FTT/BNB', 'QTUM/USDT', 'XLM/ETH', 'USDS/USDT', 'CVC/USDT', 'STPT/USDT', 'WTC/ETH', 'TRX/ETH', 'DATA/ETH', 'IOTA/BNB', 'ERD/USDT', 'WRX/USDT', 'STEEM/BNB', 'STRAT/USDT', 'CHZ/USDT', 'BCH/USDT', 'ATOM/BNB', 'XVG/ETH', 'ZRX/ETH', 'XMR/USDT', 'EOS/ETH', 'SC/ETH', 'VET/USDT', 'DENT/ETH', 'PIVX/ETH', 'BRD/ETH', 'RVN/BNB', 'ONT/BNB', 'TRX/BNB', 'DASH/BNB', 'IOST/BNB', 'QTUM/ETH', 'LTO/USDT', 'ONG/USDT', 'WAN/BNB', 'MTL/USDT', 'STRAT/ETH']

ticker_list = [
    "NULS/BTC",
    "BTS/USDT",
    "ENG/BTC",
    "BAT/ETH",
    "POWR/ETH",
    "MITH/BTC",
    "XVG/BTC",
    "BUSD/USDT",
    "ANKR/USDT",
    "THETA/BNB",
    "THETA/USDT",
    "IOTA/BNB",
    "MTL/ETH",
    "BAT/BTC",
    "KEY/USDT",
    "ZIL/BNB",
    "OST/ETH",
    "MTL/BTC",
    "SKY/BTC",
    "ZRX/ETH",
    "ZEC/BNB",
    "WRX/USDT",
    "CHR/BTC",
    "NAS/ETH",
    "EOS/USDT",
    "ETC/USDT",
    "HC/BTC",
    "BRD/BTC",
    "GXS/BTC",
    "EVX/BTC",
    "XTZ/BNB",
    "NEO/ETH",
    "ONG/USDT",
    "STRAT/USDT",
    "CMT/BTC",
    "QTUM/USDT",
    "DNT/BTC",
    "MCO/BTC",
    "LUN/BTC",
    "XZC/BTC",
    "LEND/BTC",
    "BRD/ETH",
    "MFT/ETH",
    "GTO/USDT",
    "DATA/USDT",
    "KNC/BTC",
    "TNT/ETH",
    "MATIC/USDT",
    "DOGE/USDT",
    "FTM/BNB",
    "PERL/BNB",
    "MATIC/BNB",
    "WAVES/BNB",
    "VIA/BTC",
    "QLC/ETH",
    "MTL/USDT",
    "LTC/ETH",
    "HOT/USDT",
    "MBL/USDT",
    "WAN/BTC",
    "DUSK/USDT",
    "GAS/BTC",
    "ERD/BNB",
    "AMB/BTC",
    "MDT/BNB",
    "HC/USDT",
    "FTT/USDT",
    "IOTX/BTC",
    "FET/USDT",
    "XLM/USDT",
    "BTT/BNB",
    "NAV/BTC",
    "WTC/USDT",
    "GTO/ETH",
    "BCH/BNB",
    "FUN/BTC",
    "ONT/ETH",
    "ARPA/USDT",
    "COTI/USDT",
    "WAVES/ETH",
    "ZEN/BNB",
    "CHZ/USDT",
    "VIB/ETH",
    "VITE/USDT",
    "WAN/USDT",
    "KMD/BTC",
    "WIN/USDT",
    "ONT/BTC",
    "HIVE/BNB",
    "MDT/USDT",
    "BCD/BTC",
    "NCASH/ETH",
    "AE/ETH",
    "IOTA/BTC",
    "XEM/ETH",
    "XTZ/BTC",
    "REP/ETH",
    "IOTX/USDT",
    "ENG/ETH",
    "ARN/BTC",
    "CVC/ETH",
    "DATA/ETH",
    "WAVES/USDT",
    "USDS/USDT",
    "YOYOW/BTC",
    "STEEM/ETH",
    "KNC/ETH",
    "ZEN/BTC",
    "XEM/BTC",
    "SYS/BTC",
    "FTT/BNB",
    "HBAR/BNB",
    "OST/BTC",
    "NULS/ETH",
    "THETA/ETH",
    "COS/USDT",
    "FUN/USDT",
    "RVN/BTC",
    "GNT/BTC",
    "LRC/USDT",
    "MFT/BNB",
    "AGI/BTC",
    "WAN/ETH",
    "COCOS/BNB",
    "TUSD/USDT",
    "STMX/ETH",
    "NKN/USDT",
    "XRP/BNB",
    "LSK/ETH",
    "WPR/BTC",
    "POWR/BTC",
    "ATOM/BTC",
    "XRP/BTC",
    "ADA/BNB",
    "TROY/BTC",
    "ZEC/BTC",
    "XMR/ETH",
    "ZIL/BTC",
    "XVG/ETH",
    "IOTX/ETH",
    "ONE/BTC",
    "BCH/BTC",
    "FTM/BTC",
    "DASH/ETH",
    "DREP/BTC",
    "VET/BNB",
    "STPT/BTC",
    "RLC/BNB",
    "ARDR/BTC",
    "MANA/ETH",
    "OMG/ETH",
    "WIN/BNB",
    "XRP/ETH",
    "STX/USDT",
    "DOCK/USDT",
    "CTXC/USDT",
    "MBL/BTC",
    "PERL/BTC",
    "CTSI/BNB",
    "BAT/BNB",
    "STPT/USDT",
    "NEBL/BNB",
    "CVC/BTC",
    "LTC/USDT",
    "CHR/BNB",
    "TOMO/BNB",
    "CDT/BTC",
    "NEBL/ETH",
    "WAN/BNB",
    "BEAM/BTC",
    "ETH/BTC",
    "DASH/BNB",
    "SNGLS/BTC",
    "ONE/BNB",
    "WABI/BNB",
    "TCT/BTC",
    "ZIL/ETH",
    "ETC/BTC",
    "XMR/BTC",
    "TOMO/BTC",
    "FTT/BTC",
    "MCO/ETH",
    "MFT/USDT",
    "VET/BTC",
    "KMD/ETH",
    "STORJ/BTC",
    "XMR/USDT",
    "BAND/USDT",
    "LINK/BTC",
    "FUEL/BTC",
    "ALGO/BNB",
    "CDT/ETH",
    "RVN/USDT",
    "BTCDOWN/USDT",
    "ZRX/BTC",
    "AION/BTC",
    "NPXS/USDT",
    "OGN/BTC",
    "ENJ/ETH",
    "LTC/BNB",
    "QKC/ETH",
    "FTM/USDT",
    "BAND/BNB",
    "LEND/USDT",
    "DUSK/BTC",
    "ERD/USDT",
    "AION/BNB",
    "IOST/BNB",
    "ADA/USDT",
    "BEAM/USDT",
    "ERD/BTC",
    "NEO/BNB",
    "IOTA/ETH",
    "LTO/BTC",
    "XRP/USDT",
    "DOGE/BTC",
    "NANO/ETH",
    "ZIL/USDT",
    "OAX/BTC",
    "NKN/BNB",
    "TROY/BNB",
    "TFUEL/BTC",
    "TFUEL/USDT",
    "LTC/BTC",
    "ANKR/BNB",
    "ARK/BTC",
    "NANO/BTC",
    "ATOM/BNB",
    "BNT/ETH",
    "USDC/USDT",
    "CELR/BTC",
    "HOT/BNB",
    "NEO/USDT",
    "ARN/ETH",
    "BCH/USDT",
    "XZC/BNB",
    "LRC/BTC",
    "KAVA/BNB",
    "POLY/BTC",
    "HIVE/USDT",
    "AION/ETH",
    "WTC/BTC",
    "BRD/BNB",
    "ETH/USDT",
    "SOL/BNB",
    "LOOM/ETH",
    "COS/BTC",
    "ONE/USDT",
    "CELR/BNB",
    "WRX/BTC",
    "SNT/ETH",
    "LOOM/BTC",
    "ARPA/BTC",
    "BTCUP/USDT",
    "POA/BTC",
    "OGN/BNB",
    "LSK/USDT",
    "TRX/USDT",
    "EOS/ETH",
    "QKC/BTC",
    "ENJ/USDT",
    "MITH/USDT",
    "NULS/USDT",
    "POE/BTC",
    "NAS/BTC",
    "ELF/ETH",
    "GTO/BTC",
    "COTI/BNB",
    "HIVE/BTC",
    "XZC/ETH",
    "MDT/BTC",
    "FET/BNB",
    "GXS/ETH",
    "EOS/BNB",
    "IOST/USDT",
    "GXS/USDT",
    "VITE/BTC",
    "BAT/USDT",
    "STX/BTC",
    "ALGO/USDT",
    "LEND/ETH",
    "COS/BNB",
    "ZEN/ETH",
    "ATOM/USDT",
    "RLC/BTC",
    "CTSI/BTC",
    "XTZ/USDT",
    "ZRX/USDT",
    "ICX/BTC",
    "TRX/BTC",
    "CHZ/BTC",
    "BTS/BTC",
    "TNB/BTC",
    "KEY/ETH",
    "DENT/USDT",
    "NANO/USDT",
    "CMT/ETH",
    "CHZ/BNB",
    "NEO/BTC",
    "MATIC/BTC",
    "OMG/USDT",
    "LRC/ETH",
    "WABI/BTC",
    "WTC/ETH",
    "KAVA/USDT",
    "DATA/BTC",
    "WAVES/BTC",
    "ADX/ETH",
    "BTG/BTC",
    "QTUM/ETH",
    "STRAT/BTC",
    "XMR/BNB",
    "ICX/ETH",
    "PIVX/BTC",
    "LINK/ETH",
    "GVT/BTC",
    "NXS/BTC",
    "NPXS/ETH",
    "VET/USDT",
    "XZC/USDT",
    "STMX/USDT",
    "AE/BTC",
    "APPC/BTC",
    "PAX/USDT",
    "BTT/USDT",
    "CVC/USDT",
    "SC/ETH",
    "MBL/BNB",
    "STRAT/ETH",
    "KNC/USDT",
    "ONT/BNB",
    "RLC/USDT",
    "DOCK/BTC",
    "ALGO/BTC",
    "BLZ/BNB",
    "CTXC/BTC",
    "GO/BTC",
    "IOST/ETH",
    "BNT/USDT",
    "IOTA/USDT",
    "BQX/ETH",
    "MTH/BTC",
    "ONG/BTC",
    "REN/USDT",
    "ENJ/BNB",
    "LTO/USDT",
    "WTC/BNB",
    "BAND/BTC",
    "ARPA/BNB",
    "CTSI/USDT",
    "CND/BTC",
    "BNB/USDT",
    "KAVA/BTC",
    "ADA/BTC",
    "PERL/USDT",
    "ICX/USDT",
    "HOT/ETH",
    "MANA/BTC",
    "ANKR/BTC",
    "DREP/USDT",
    "LSK/BTC",
    "INS/BTC",
    "BLZ/ETH",
    "TOMO/USDT",
    "REP/USDT",
    "STEEM/BNB",
    "NEBL/BTC",
    "ZEC/USDT",
    "STX/BNB",
    "ZEC/ETH",
    "VIBE/BTC",
    "ONT/USDT",
    "PHB/BTC",
    "REN/BTC",
    "AION/USDT",
    "HOT/BTC",
    "RLC/ETH",
    "CELR/USDT",
    "BLZ/BTC",
    "COCOS/USDT",
    "EUR/USDT",
    "BQX/BTC",
    "RDN/BTC",
    "TRX/BNB",
    "HBAR/BTC",
    "STORJ/ETH",
    "THETA/BTC",
    "PIVX/ETH",
    "BNB/BTC",
    "ENJ/BTC",
    "SNT/BTC",
    "IQ/BNB",
    "ETC/BNB",
    "DASH/BTC",
    "SC/BTC",
    "REP/BTC",
    "CHR/USDT",
    "ETC/ETH",
    "GNT/ETH",
    "FET/BTC",
    "DENT/ETH",
    "XLM/ETH",
    "ARDR/USDT",
    "QSP/BTC",
    "TROY/USDT",
    "SOL/BTC",
    "OGN/USDT",
    "BCPT/BTC",
    "ZRX/BNB",
    "SC/BNB",
    "REQ/BTC",
    "RCN/BTC",
    "TCT/USDT",
    "LINK/USDT",
    "STMX/BTC",
    "QSP/ETH",
    "XLM/BNB",
    "DLT/BTC",
    "ADA/ETH",
    "STMX/BNB",
    "WRX/BNB",
    "IOST/BTC",
    "COTI/BTC",
    "QLC/BTC",
    "TNT/BTC",
    "XLM/BTC",
    "EOS/BTC",
    "GRS/BTC",
    "SNM/BTC",
    "ADX/BTC",
    "DASH/USDT",
    "HBAR/USDT",
    "ELF/BTC",
    "BNB/ETH",
    "TRX/ETH",
    "QTUM/BTC",
    "VET/ETH",
    "MCO/USDT",
    "ICX/BNB",
    "PPT/BTC",
    "DOCK/ETH",
    "MITH/BNB",
    "BTC/USDT",
    "OMG/BTC",
    "VIB/BTC",
    "EVX/ETH",
    "NKN/BTC",
    "STEEM/BTC",
    "FUN/ETH",
    "DCR/BTC",
    "BNT/BTC",
    "MDA/BTC",
    "AST/BTC",
    "RVN/BNB",
]


def temp_func(day):
    print("")


"""
for i in range(2,60):
    print('day = ', i)
    temp_func(i)
"""


def get_time(temp):
    now = temp
    YYYY = str(now.year)
    MM = str(now.month)
    DD = str(now.day)
    hh = str(now.hour)
    mm = str(now.minute)

    if len(MM) != 2:
        MM = "0" + MM
    if len(DD) != 2:
        DD = "0" + DD
    if len(hh) != 2:
        hh = "0" + hh
    if len(mm) != 2:
        mm = "0" + mm

    return YYYY + MM + DD, hh + mm


a, b = get_time(datetime.datetime.now())
print(b)

for i in range(2, 60):

    print("day", i, ":")
    temp_func(i)

a, b = get_time(datetime.datetime.now())
print(b)
