import ccxt
import time
from pprint import pprint


def get_tickers(base):
    # base = '/USDT' or '/BNB' or '/BTC' or ...
    All_ticker = binance.fetch_tickers().keys()
    tickers = [s for s in All_ticker if base in s]
    result = []
    for i, item in enumerate(tickers):
        ohlcv = binance.fetch_order_book(item)
        if len(ohlcv["bids"]) != 0:
            result.append(item)
    return result


binance = ccxt.binance(
    {
        "apiKey": "3pFJ5lblk8ff8brlz2plOG2o",
        "secret": "KKFk0a-YvtW8aEcS33HbQlxJ63rHpdA95D7IWNALSOTVraB1",
        "enableRateLimit": True,
        "RateLimit": 10000,
    }
)
binance.load_markets()


time_frame = "1d"


# ticker_list = list(set(get_tickers('/ETH')) | set(get_tickers('/BNB')) | set(get_tickers('/USDT')) | set(get_tickers('/BTC')))

# ticker_list = ['WTC/BNB', 'GTO/ETH', 'FTM/BNB', 'THETA/ETH', 'XLM/BNB', 'WIN/USDT', 'ATOM/USDT', 'NULS/USDT', 'XZC/ETH', 'HC/USDT', 'KEY/ETH', 'IOTA/ETH', 'ZEC/ETH', 'ADA/ETH', 'ZEN/ETH', 'POWR/ETH', 'LOOM/ETH', 'TROY/USDT', 'MFT/ETH', 'ZIL/USDT', 'TOMO/BNB', 'BNB/ETH', 'ICX/USDT', 'XRP/USDT', 'DOCK/USDT', 'BTCUP/USDT', 'BQX/ETH', 'ETC/ETH', 'WAVES/ETH', 'NPXS/ETH', 'HOT/ETH', 'LEND/USDT', 'HOT/USDT', 'ZRX/BNB', 'WAN/ETH', 'ALGO/BNB', 'WRX/BNB', 'MDT/USDT', 'ADA/USDT', 'NULS/ETH', 'BLZ/ETH', 'XMR/ETH', 'COS/BNB', 'IQ/BNB', 'PERL/BNB', 'NPXS/USDT', 'MCO/USDT', 'OMG/USDT', 'FET/USDT', 'LEND/ETH', 'EUR/USDT', 'LTC/ETH', 'WAVES/USDT', 'ICX/BNB', 'NKN/USDT', 'ZEC/BNB', 'KEY/USDT', 'LRC/ETH', 'LSK/ETH', 'WIN/BNB', 'PERL/USDT', 'ZIL/ETH', 'MANA/ETH', 'NEO/BNB', 'XTZ/BNB', 'FUN/USDT', 'THETA/BNB', 'BNT/ETH', 'GNT/ETH', 'TROY/BNB', 'WTC/USDT', 'MBL/BNB', 'STEEM/ETH', 'RLC/ETH', 'AION/ETH', 'DOCK/ETH', 'CHZ/BNB', 'CELR/BNB', 'STX/BNB', 'LRC/USDT', 'XRP/ETH', 'MITH/BNB', 'BTS/USDT', 'PAX/USDT', 'BTT/USDT', 'ARPA/USDT', 'BAT/ETH', 'CTXC/USDT', 'BTCDOWN/USDT', 'OST/ETH', 'DATA/USDT', 'HIVE/BNB', 'KAVA/BNB', 'MCO/ETH', 'GTO/USDT', 'ETC/BNB', 'KAVA/USDT', 'RLC/USDT', 'NANO/USDT', 'ELF/ETH', 'MFT/USDT', 'CTSI/USDT', 'FTT/USDT', 'SNT/ETH', 'KNC/ETH', 'MBL/USDT', 'ZRX/USDT', 'XTZ/USDT', 'BRD/BNB', 'QKC/ETH', 'DUSK/USDT', 'EOS/BNB', 'STMX/BNB', 'HBAR/USDT', 'GXS/ETH', 'NEO/ETH', 'QSP/ETH', 'ADX/ETH', 'MFT/BNB', 'MATIC/BNB', 'NEBL/BNB', 'REN/USDT', 'ARDR/USDT', 'VITE/USDT', 'XEM/ETH', 'MDT/BNB', 'ANKR/BNB', 'HIVE/USDT', 'BTT/BNB', 'ONT/ETH', 'IOTX/ETH', 'VET/ETH', 'ICX/ETH', 'ARPA/BNB', 'DREP/USDT', 'REP/ETH', 'ZEN/BNB', 'TUSD/USDT', 'IOST/ETH', 'USDC/USDT', 'EOS/USDT', 'LSK/USDT', 'ONT/USDT', 'XZC/USDT', 'OGN/BNB', 'LINK/USDT', 'DASH/ETH', 'ARN/ETH', 'SC/BNB', 'CTSI/BNB', 'ETC/USDT', 'BAT/USDT', 'SOL/BNB', 'ENJ/BNB', 'LTC/USDT', 'REP/USDT', 'ONE/BNB', 'CHR/BNB', 'BUSD/USDT', 'MITH/USDT', 'STORJ/ETH', 'OGN/USDT', 'STMX/ETH', 'XMR/BNB', 'TRX/USDT', 'XLM/USDT', 'ADA/BNB', 'COTI/BNB', 'HBAR/BNB', 'BLZ/BNB', 'ENJ/USDT', 'FUN/ETH', 'NAS/ETH', 'ONE/USDT', 'BAT/BNB', 'CELR/USDT', 'ZIL/BNB', 'KNC/USDT', 'BNB/USDT', 'TOMO/USDT', 'ETH/USDT', 'MATIC/USDT', 'FTM/USDT', 'HOT/BNB', 'IOTA/USDT', 'COTI/USDT', 'CMT/ETH', 'BAND/BNB', 'DOGE/USDT', 'AE/ETH', 'NCASH/ETH', 'STMX/USDT', 'GXS/USDT', 'COS/USDT', 'VIB/ETH', 'ERD/BNB', 'BCH/BNB', 'BNT/USDT', 'DASH/USDT', 'QLC/ETH', 'BEAM/USDT', 'EVX/ETH', 'VET/BNB', 'NKN/BNB', 'WAN/USDT', 'ANKR/USDT', 'OMG/ETH', 'STX/USDT', 'BAND/USDT', 'NANO/ETH', 'ENG/ETH', 'TNT/ETH', 'ALGO/USDT', 'DENT/USDT', 'TCT/USDT', 'THETA/USDT', 'NEO/USDT', 'LINK/ETH', 'NEBL/ETH', 'WABI/BNB', 'LTC/BNB', 'TFUEL/USDT', 'ZEC/USDT', 'KMD/ETH', 'RLC/BNB', 'FET/BNB', 'WAVES/BNB', 'AION/BNB', 'IOST/USDT', 'RVN/USDT', 'CHR/USDT', 'ENJ/ETH', 'BTC/USDT', 'IOTX/USDT', 'AION/USDT', 'CDT/ETH', 'CVC/ETH', 'MTL/ETH', 'COCOS/USDT', 'COCOS/BNB', 'XZC/BNB', 'XRP/BNB', 'FTT/BNB', 'QTUM/USDT', 'XLM/ETH', 'USDS/USDT', 'CVC/USDT', 'STPT/USDT', 'WTC/ETH', 'TRX/ETH', 'DATA/ETH', 'IOTA/BNB', 'ERD/USDT', 'WRX/USDT', 'STEEM/BNB', 'STRAT/USDT', 'CHZ/USDT', 'BCH/USDT', 'ATOM/BNB', 'XVG/ETH', 'ZRX/ETH', 'XMR/USDT', 'EOS/ETH', 'SC/ETH', 'VET/USDT', 'DENT/ETH', 'PIVX/ETH', 'BRD/ETH', 'RVN/BNB', 'ONT/BNB', 'TRX/BNB', 'DASH/BNB', 'IOST/BNB', 'QTUM/ETH', 'LTO/USDT', 'ONG/USDT', 'WAN/BNB', 'MTL/USDT', 'STRAT/ETH']

# ticker_list = ['NULS/BTC', 'BTS/USDT', 'ENG/BTC', 'BAT/ETH', 'POWR/ETH', 'MITH/BTC', 'XVG/BTC', 'BUSD/USDT', 'ANKR/USDT', 'THETA/BNB', 'THETA/USDT', 'IOTA/BNB', 'MTL/ETH', 'BAT/BTC', 'KEY/USDT', 'ZIL/BNB', 'OST/ETH', 'MTL/BTC', 'SKY/BTC', 'ZRX/ETH', 'ZEC/BNB', 'WRX/USDT', 'CHR/BTC', 'NAS/ETH', 'EOS/USDT', 'ETC/USDT', 'HC/BTC', 'BRD/BTC', 'GXS/BTC', 'EVX/BTC', 'XTZ/BNB', 'NEO/ETH', 'ONG/USDT', 'STRAT/USDT', 'CMT/BTC', 'QTUM/USDT', 'DNT/BTC', 'MCO/BTC', 'LUN/BTC', 'XZC/BTC', 'LEND/BTC', 'BRD/ETH', 'MFT/ETH', 'GTO/USDT', 'DATA/USDT', 'KNC/BTC', 'TNT/ETH', 'MATIC/USDT', 'DOGE/USDT', 'FTM/BNB', 'PERL/BNB', 'MATIC/BNB', 'WAVES/BNB', 'VIA/BTC', 'QLC/ETH', 'MTL/USDT', 'LTC/ETH', 'HOT/USDT', 'MBL/USDT', 'WAN/BTC', 'DUSK/USDT', 'GAS/BTC', 'ERD/BNB', 'AMB/BTC', 'MDT/BNB', 'HC/USDT', 'FTT/USDT', 'IOTX/BTC', 'FET/USDT', 'XLM/USDT', 'BTT/BNB', 'NAV/BTC', 'WTC/USDT', 'GTO/ETH', 'BCH/BNB', 'FUN/BTC', 'ONT/ETH', 'ARPA/USDT', 'COTI/USDT', 'WAVES/ETH', 'ZEN/BNB', 'CHZ/USDT', 'VIB/ETH', 'VITE/USDT', 'WAN/USDT', 'KMD/BTC', 'WIN/USDT', 'ONT/BTC', 'HIVE/BNB', 'MDT/USDT', 'BCD/BTC', 'NCASH/ETH', 'AE/ETH', 'IOTA/BTC', 'XEM/ETH', 'XTZ/BTC', 'REP/ETH', 'IOTX/USDT', 'ENG/ETH', 'ARN/BTC', 'CVC/ETH', 'DATA/ETH', 'WAVES/USDT', 'USDS/USDT', 'YOYOW/BTC', 'STEEM/ETH', 'KNC/ETH', 'ZEN/BTC', 'XEM/BTC', 'SYS/BTC', 'FTT/BNB', 'HBAR/BNB', 'OST/BTC', 'NULS/ETH', 'THETA/ETH', 'COS/USDT', 'FUN/USDT', 'RVN/BTC', 'GNT/BTC', 'LRC/USDT', 'MFT/BNB', 'AGI/BTC', 'WAN/ETH', 'COCOS/BNB', 'TUSD/USDT', 'STMX/ETH', 'NKN/USDT', 'XRP/BNB', 'LSK/ETH', 'WPR/BTC', 'POWR/BTC', 'ATOM/BTC', 'XRP/BTC', 'ADA/BNB', 'TROY/BTC', 'ZEC/BTC', 'XMR/ETH', 'ZIL/BTC', 'XVG/ETH', 'IOTX/ETH', 'ONE/BTC', 'BCH/BTC', 'FTM/BTC', 'DASH/ETH', 'DREP/BTC', 'VET/BNB', 'STPT/BTC', 'RLC/BNB', 'ARDR/BTC', 'MANA/ETH', 'OMG/ETH', 'WIN/BNB', 'XRP/ETH', 'STX/USDT', 'DOCK/USDT', 'CTXC/USDT', 'MBL/BTC', 'PERL/BTC', 'CTSI/BNB', 'BAT/BNB', 'STPT/USDT', 'NEBL/BNB', 'CVC/BTC', 'LTC/USDT', 'CHR/BNB', 'TOMO/BNB', 'CDT/BTC', 'NEBL/ETH', 'WAN/BNB', 'BEAM/BTC', 'ETH/BTC', 'DASH/BNB', 'SNGLS/BTC', 'ONE/BNB', 'WABI/BNB', 'TCT/BTC', 'ZIL/ETH', 'ETC/BTC', 'XMR/BTC', 'TOMO/BTC', 'FTT/BTC', 'MCO/ETH', 'MFT/USDT', 'VET/BTC', 'KMD/ETH', 'STORJ/BTC', 'XMR/USDT', 'BAND/USDT', 'LINK/BTC', 'FUEL/BTC', 'ALGO/BNB', 'CDT/ETH', 'RVN/USDT', 'BTCDOWN/USDT', 'ZRX/BTC', 'AION/BTC', 'NPXS/USDT', 'OGN/BTC', 'ENJ/ETH', 'LTC/BNB', 'QKC/ETH', 'FTM/USDT', 'BAND/BNB', 'LEND/USDT', 'DUSK/BTC', 'ERD/USDT', 'AION/BNB', 'IOST/BNB', 'ADA/USDT', 'BEAM/USDT', 'ERD/BTC', 'NEO/BNB', 'IOTA/ETH', 'LTO/BTC', 'XRP/USDT', 'DOGE/BTC', 'NANO/ETH', 'ZIL/USDT', 'OAX/BTC', 'NKN/BNB', 'TROY/BNB', 'TFUEL/BTC', 'TFUEL/USDT', 'LTC/BTC', 'ANKR/BNB', 'ARK/BTC', 'NANO/BTC', 'ATOM/BNB', 'BNT/ETH', 'USDC/USDT', 'CELR/BTC', 'HOT/BNB', 'NEO/USDT', 'ARN/ETH', 'BCH/USDT', 'XZC/BNB', 'LRC/BTC', 'KAVA/BNB', 'POLY/BTC', 'HIVE/USDT', 'AION/ETH', 'WTC/BTC', 'BRD/BNB', 'ETH/USDT', 'SOL/BNB', 'LOOM/ETH', 'COS/BTC', 'ONE/USDT', 'CELR/BNB', 'WRX/BTC', 'SNT/ETH', 'LOOM/BTC', 'ARPA/BTC', 'BTCUP/USDT', 'POA/BTC', 'OGN/BNB', 'LSK/USDT', 'TRX/USDT', 'EOS/ETH', 'QKC/BTC', 'ENJ/USDT', 'MITH/USDT', 'NULS/USDT', 'POE/BTC', 'NAS/BTC', 'ELF/ETH', 'GTO/BTC', 'COTI/BNB', 'HIVE/BTC', 'XZC/ETH', 'MDT/BTC', 'FET/BNB', 'GXS/ETH', 'EOS/BNB', 'IOST/USDT', 'GXS/USDT', 'VITE/BTC', 'BAT/USDT', 'STX/BTC', 'ALGO/USDT', 'LEND/ETH', 'COS/BNB', 'ZEN/ETH', 'ATOM/USDT', 'RLC/BTC', 'CTSI/BTC', 'XTZ/USDT', 'ZRX/USDT', 'ICX/BTC', 'TRX/BTC', 'CHZ/BTC', 'BTS/BTC', 'TNB/BTC', 'KEY/ETH', 'DENT/USDT', 'NANO/USDT', 'CMT/ETH', 'CHZ/BNB', 'NEO/BTC', 'MATIC/BTC', 'OMG/USDT', 'LRC/ETH', 'WABI/BTC', 'WTC/ETH', 'KAVA/USDT', 'DATA/BTC', 'WAVES/BTC', 'ADX/ETH', 'BTG/BTC', 'QTUM/ETH', 'STRAT/BTC', 'XMR/BNB', 'ICX/ETH', 'PIVX/BTC', 'LINK/ETH', 'GVT/BTC', 'NXS/BTC', 'NPXS/ETH', 'VET/USDT', 'XZC/USDT', 'STMX/USDT', 'AE/BTC', 'APPC/BTC', 'PAX/USDT', 'BTT/USDT', 'CVC/USDT', 'SC/ETH', 'MBL/BNB', 'STRAT/ETH', 'KNC/USDT', 'ONT/BNB', 'RLC/USDT', 'DOCK/BTC', 'ALGO/BTC', 'BLZ/BNB', 'CTXC/BTC', 'GO/BTC', 'IOST/ETH', 'BNT/USDT', 'IOTA/USDT', 'BQX/ETH', 'MTH/BTC', 'ONG/BTC', 'REN/USDT', 'ENJ/BNB', 'LTO/USDT', 'WTC/BNB', 'BAND/BTC', 'ARPA/BNB', 'CTSI/USDT', 'CND/BTC', 'BNB/USDT', 'KAVA/BTC', 'ADA/BTC', 'PERL/USDT', 'ICX/USDT', 'HOT/ETH', 'MANA/BTC', 'ANKR/BTC', 'DREP/USDT', 'LSK/BTC', 'INS/BTC', 'BLZ/ETH', 'TOMO/USDT', 'REP/USDT', 'STEEM/BNB', 'NEBL/BTC', 'ZEC/USDT', 'STX/BNB', 'ZEC/ETH', 'VIBE/BTC', 'ONT/USDT', 'PHB/BTC', 'REN/BTC', 'AION/USDT', 'HOT/BTC', 'RLC/ETH', 'CELR/USDT', 'BLZ/BTC', 'COCOS/USDT', 'EUR/USDT', 'BQX/BTC', 'RDN/BTC', 'TRX/BNB', 'HBAR/BTC', 'STORJ/ETH', 'THETA/BTC', 'PIVX/ETH', 'BNB/BTC', 'ENJ/BTC', 'SNT/BTC', 'IQ/BNB', 'ETC/BNB', 'DASH/BTC', 'SC/BTC', 'REP/BTC', 'CHR/USDT', 'ETC/ETH', 'GNT/ETH', 'FET/BTC', 'DENT/ETH', 'XLM/ETH', 'ARDR/USDT', 'QSP/BTC', 'TROY/USDT', 'SOL/BTC', 'OGN/USDT', 'BCPT/BTC', 'ZRX/BNB', 'SC/BNB', 'REQ/BTC', 'BCN/ETH', 'RCN/BTC', 'TCT/USDT', 'LINK/USDT', 'STMX/BTC', 'QSP/ETH', 'XLM/BNB', 'DLT/BTC', 'ADA/ETH', 'STMX/BNB', 'WRX/BNB', 'IOST/BTC', 'COTI/BTC', 'QLC/BTC', 'TNT/BTC', 'XLM/BTC', 'EOS/BTC', 'GRS/BTC', 'SNM/BTC', 'ADX/BTC', 'DASH/USDT', 'HBAR/USDT', 'ELF/BTC', 'BNB/ETH', 'TRX/ETH', 'QTUM/BTC', 'VET/ETH', 'MCO/USDT', 'ICX/BNB', 'PPT/BTC', 'DOCK/ETH', 'MITH/BNB', 'BTC/USDT', 'OMG/BTC', 'VIB/BTC', 'EVX/ETH', 'NKN/BTC', 'STEEM/BTC', 'FUN/ETH', 'DCR/BTC', 'BNT/BTC', 'MDA/BTC', 'AST/BTC', 'RVN/BNB']

# ticker_list = ['ENJ/BNB', 'ATOM/USDT', 'LTC/BNB', 'BNB/USDT', 'FET/BTC', 'STEEM/BTC', 'OMG/BTC', 'EOS/BTC', 'RVN/BTC', 'BTC/USDT', 'TROY/USDT', 'MBL/USDT', 'COS/BNB', 'CHR/USDT', 'MTH/BTC', 'EVX/BTC', 'LUN/BTC', 'MBL/BNB', 'FTM/BTC', 'DENT/USDT', 'ZRX/BTC', 'ZEN/BTC', 'FET/BNB', 'DNT/BTC', 'MCO/BTC', 'LRC/USDT', 'DOGE/BTC', 'MFT/BNB', 'PAX/USDT', 'PNT/BTC', 'SNGLS/BTC', 'LTO/BTC', 'ETC/USDT', 'COCOS/USDT', 'FTT/BNB', 'AION/USDT', 'PERL/BTC', 'IOTA/BNB', 'ATOM/BTC', 'MITH/BNB', 'BCD/BTC', 'GVT/BTC', 'TRX/BNB', 'TNB/BTC', 'SOL/BTC', 'TRX/BTC', 'CDT/BTC', 'ZIL/BTC', 'WIN/USDT', 'NAS/BTC', 'NEBL/BNB', 'OGN/USDT', 'ZRX/USDT', 'WAVES/BNB', 'BNT/USDT', 'NANO/BTC', 'ONG/BTC', 'ADA/BTC', 'WAN/USDT', 'AGI/BTC', 'DREP/BTC', 'WRX/BTC', 'DGB/BTC', 'EOS/USDT', 'NEO/USDT', 'XZC/USDT', 'MTL/USDT', 'FUN/USDT', 'KNC/USDT', 'COCOS/BNB', 'WIN/BNB', 'HBAR/BTC', 'TOMO/BNB', 'REP/USDT', 'ARK/BTC', 'COTI/USDT', 'WABI/BNB', 'ZEC/BTC', 'TROY/BTC', 'KAVA/BNB', 'MBL/BTC', 'XTZ/USDT', 'MDT/BNB', 'ZEN/BNB', 'ALGO/BTC', 'LEND/BTC', 'ONE/BTC', 'TCT/USDT', 'CTSI/BNB', 'DASH/USDT', 'CVC/BTC', 'MATIC/BNB', 'OGN/BTC', 'OGN/BNB', 'ENJ/USDT', 'POA/BTC', 'TRX/USDT', 'SNT/BTC', 'USDC/USDT', 'QTUM/BTC', 'SC/BNB', 'ENJ/BTC', 'BCH/USDT', 'XZC/BNB', 'FET/USDT', 'REN/USDT', 'NEBL/BTC', 'MCO/USDT', 'ONG/USDT', 'AMB/BTC', 'POWR/BTC', 'STRAT/BTC', 'WTC/BTC', 'IOTX/USDT', 'WAVES/BTC', 'BEAM/USDT', 'ETH/BTC', 'DUSK/BTC', 'LTC/BTC', 'THETA/BTC', 'SC/BTC', 'EUR/USDT', 'LTC/USDT', 'BTT/USDT', 'LINK/USDT', 'XVG/BTC', 'BTS/BTC', 'OAX/BTC', 'BTT/BNB', 'VET/BNB', 'ONT/BTC', 'YOYOW/BTC', 'XRP/BTC', 'PERL/USDT', 'SKY/BTC', 'PNT/USDT', 'MDA/BTC', 'MITH/USDT', 'QKC/BTC', 'WRX/USDT', 'LSK/BTC', 'THETA/BNB', 'STMX/BNB', 'SNM/BTC', 'NKN/BNB', 'ETC/BTC', 'WAN/BNB', 'ANKR/BTC', 'IQ/BNB', 'RVN/BNB', 'VET/USDT', 'ZEC/BNB', 'BUSD/USDT', 'BAND/BNB', 'PERL/BNB', 'BTCUP/USDT', 'CTXC/USDT', 'XLM/USDT', 'MANA/BTC', 'CHR/BNB', 'COTI/BNB', 'NANO/USDT', 'STEEM/BNB', 'HOT/USDT', 'HOT/BNB', 'ONT/BNB', 'OMG/USDT', 'LRC/BTC', 'FUN/BTC', 'ETC/BNB', 'DATA/BTC', 'ARPA/BTC', 'ARPA/BNB', 'MDT/USDT', 'OST/BTC', 'NXS/BTC', 'ADA/USDT', 'POLY/BTC', 'NKN/USDT', 'POE/BTC', 'WAVES/USDT', 'WAN/BTC', 'CELR/BNB', 'HIVE/BNB', 'LEND/USDT', 'IOTX/BTC', 'ZIL/BNB', 'KAVA/USDT', 'LSK/USDT', 'XMR/BTC', 'RLC/BNB', 'CND/BTC', 'FTT/USDT', 'IOST/USDT', 'REN/BTC', 'DOCK/BTC', 'KNC/BTC', 'PHB/BTC', 'SYS/BTC', 'STX/BTC', 'RLC/USDT', 'DOCK/USDT', 'IOTA/BTC', 'ENG/BTC', 'TROY/BNB', 'DLT/BTC', 'CHZ/BTC', 'ANKR/USDT', 'ARDR/USDT', 'XMR/USDT', 'VIA/BTC', 'CMT/BTC', 'AST/BTC', 'APPC/BTC', 'TFUEL/BTC', 'HC/USDT', 'LOOM/BTC', 'DOGE/USDT', 'AION/BNB', 'HIVE/BTC', 'CTSI/USDT', 'NEO/BTC', 'BAT/USDT', 'XTZ/BTC', 'BAT/BTC', 'THETA/USDT', 'CHZ/USDT', 'VET/BTC', 'BAND/BTC', 'ELF/BTC', 'GO/BTC', 'NKN/BTC', 'MITH/BTC', 'PIVX/BTC', 'ERD/USDT', 'MATIC/BTC', 'ICX/BNB', 'VIBE/BTC', 'RDN/BTC', 'QSP/BTC', 'ARN/BTC', 'WTC/USDT', 'BCH/BTC', 'XTZ/BNB', 'TFUEL/USDT', 'WPR/BTC', 'MATIC/USDT', 'VITE/USDT', 'TOMO/USDT', 'CELR/USDT', 'HBAR/BNB', 'NAV/BTC', 'DCR/BTC', 'DATA/USDT', 'QLC/BTC', 'NEO/BNB', 'ARPA/USDT', 'GNT/BTC', 'XEM/BTC', 'NULS/BTC', 'BRD/BTC', 'ZEC/USDT', 'HC/BTC', 'BTG/BTC', 'IOTA/USDT', 'HOT/BTC', 'BQX/BTC', 'STORJ/BTC', 'CHZ/BNB', 'ATOM/BNB', 'BAT/BNB', 'TCT/BTC', 'BRD/BNB', 'COS/BTC', 'MFT/USDT', 'KMD/BTC', 'REP/BTC', 'ALGO/USDT', 'LTO/USDT', 'REQ/BTC', 'AE/BTC', 'TOMO/BTC', 'CELR/BTC', 'ARDR/BTC', 'XRP/BNB', 'BLZ/BTC', 'ERD/BTC', 'NPXS/USDT', 'ONE/USDT', 'ONE/BNB', 'ZRX/BNB', 'LINK/BTC', 'COTI/BTC', 'WTC/BNB', 'XRP/USDT', 'RLC/BTC', 'XZC/BTC', 'NULS/USDT', 'RCN/BTC', 'KEY/USDT', 'BNB/BTC', 'WABI/BTC', 'ICX/BTC', 'STMX/USDT', 'CVC/USDT', 'FUEL/BTC', 'BNT/BTC', 'PPT/BTC', 'BTCDOWN/USDT', 'TUSD/USDT', 'XLM/BTC', 'TNT/BTC', 'KAVA/BTC', 'ICX/USDT', 'GXS/BTC', 'ERD/BNB', 'STPT/USDT', 'BLZ/BNB', 'CTSI/BTC', 'CTXC/BTC', 'FTM/USDT', 'BCPT/BTC', 'HBAR/USDT', 'GTO/BTC', 'IOST/BNB', 'BEAM/BTC', 'STX/BNB', 'STRAT/USDT', 'XLM/BNB', 'VIB/BTC', 'IOST/BTC', 'ADA/BNB', 'ADX/BTC', 'QTUM/USDT', 'INS/BTC', 'CHR/BTC', 'FTT/BTC', 'AION/BTC', 'XMR/BNB', 'BCH/BNB', 'MTL/BTC', 'BAND/USDT', 'EOS/BNB', 'ZIL/USDT', 'DUSK/USDT', 'ONT/USDT', 'SOL/BNB', 'GTO/USDT', 'ALGO/BNB', 'FTM/BNB', 'BTS/USDT', 'DASH/BNB', 'HIVE/USDT', 'DREP/USDT', 'STMX/BTC', 'DGB/BNB', 'GXS/USDT', 'ETH/USDT', 'DASH/BTC', 'COS/USDT', 'STPT/BTC', 'STX/USDT', 'VITE/BTC', 'MDT/BTC', 'ANKR/BNB', 'GRS/BTC', 'RVN/USDT', 'GAS/BTC', 'WRX/BNB']


def temp_func(day):
    count = 0
    temp = []
    for i, item in enumerate(ticker_list):
        try:
            # time.sleep(1)
            ohlcv = binance.fetch_ohlcv(item, time_frame)
            PP = (
                ohlcv[-(day + 1)][2] + ohlcv[-(day + 1)][3] + (ohlcv[-(day + 1)][4] * 2)
            ) / 4
            R2 = PP + ohlcv[-(day + 1)][2] - ohlcv[-(day + 1)][3]
            # R3 = ohlcv[-(day+1)][2] + 2*(PP-ohlcv[-(day+1)][3])
            # R1 = 2*PP - ohlcv[-(day+1)][3]
            # S1 = 2*PP - ohlcv[-(day+1)][2]
            # S2 = PP - ohlcv[-(day+1)][2] + ohlcv[-(day+1)][3]
            R3 = ohlcv[-(day + 1)][2] + 2 * (PP - ohlcv[-(day + 1)][3])

            if ohlcv[-day][4] > R2:
                earning = round(
                    -100.22 + ohlcv[-day + 1][4] / ohlcv[-day + 1][1] * 100, 5
                )
                # print(item, earning, '%수익')
                # print('buy :',round(R2,5), 'sell :',ohlcv[-day][4])
                count += 1
                temp.append(earning)
                # print('')
        except:
            # print(item + '에러-------------------------------------------')
            print("", end="", flush=True)
    print(count)
    print(sum(temp))
    print("")


ticker_list = [
    "ENJ/BNB",
    "ATOM/USDT",
    "LTC/BNB",
    "BNB/USDT",
    "FET/BTC",
    "STEEM/BTC",
    "OMG/BTC",
    "EOS/BTC",
    "RVN/BTC",
    "BTC/USDT",
    "TROY/USDT",
    "MBL/USDT",
    "COS/BNB",
    "CHR/USDT",
    "MTH/BTC",
    "EVX/BTC",
    "LUN/BTC",
    "MBL/BNB",
    "FTM/BTC",
    "DENT/USDT",
    "ZRX/BTC",
    "ZEN/BTC",
    "FET/BNB",
    "DNT/BTC",
    "MCO/BTC",
    "LRC/USDT",
    "DOGE/BTC",
    "MFT/BNB",
    "PAX/USDT",
    "PNT/BTC",
    "SNGLS/BTC",
    "LTO/BTC",
    "ETC/USDT",
    "COCOS/USDT",
    "FTT/BNB",
    "AION/USDT",
    "PERL/BTC",
    "IOTA/BNB",
    "ATOM/BTC",
    "MITH/BNB",
    "BCD/BTC",
    "GVT/BTC",
    "TRX/BNB",
    "TNB/BTC",
    "SOL/BTC",
    "TRX/BTC",
    "CDT/BTC",
    "ZIL/BTC",
    "WIN/USDT",
    "NAS/BTC",
    "NEBL/BNB",
    "OGN/USDT",
    "ZRX/USDT",
    "WAVES/BNB",
    "BNT/USDT",
    "NANO/BTC",
    "ONG/BTC",
    "ADA/BTC",
    "WAN/USDT",
    "AGI/BTC",
    "DREP/BTC",
    "WRX/BTC",
    "DGB/BTC",
    "EOS/USDT",
    "NEO/USDT",
    "XZC/USDT",
    "MTL/USDT",
    "FUN/USDT",
    "KNC/USDT",
    "COCOS/BNB",
    "WIN/BNB",
    "HBAR/BTC",
    "TOMO/BNB",
    "REP/USDT",
    "ARK/BTC",
    "COTI/USDT",
    "WABI/BNB",
    "ZEC/BTC",
    "TROY/BTC",
    "KAVA/BNB",
    "MBL/BTC",
    "XTZ/USDT",
    "MDT/BNB",
    "ZEN/BNB",
    "ALGO/BTC",
    "LEND/BTC",
    "ONE/BTC",
    "TCT/USDT",
    "CTSI/BNB",
    "DASH/USDT",
    "CVC/BTC",
    "MATIC/BNB",
    "OGN/BTC",
    "OGN/BNB",
    "ENJ/USDT",
    "POA/BTC",
    "TRX/USDT",
    "SNT/BTC",
    "USDC/USDT",
    "QTUM/BTC",
    "SC/BNB",
    "ENJ/BTC",
    "BCH/USDT",
    "XZC/BNB",
    "FET/USDT",
    "REN/USDT",
    "NEBL/BTC",
    "MCO/USDT",
    "ONG/USDT",
    "AMB/BTC",
    "POWR/BTC",
    "STRAT/BTC",
    "WTC/BTC",
    "IOTX/USDT",
    "WAVES/BTC",
    "BEAM/USDT",
    "ETH/BTC",
    "DUSK/BTC",
    "LTC/BTC",
    "THETA/BTC",
    "SC/BTC",
    "EUR/USDT",
    "LTC/USDT",
    "BTT/USDT",
    "LINK/USDT",
    "XVG/BTC",
    "BTS/BTC",
    "OAX/BTC",
    "BTT/BNB",
    "VET/BNB",
    "ONT/BTC",
    "YOYOW/BTC",
    "XRP/BTC",
    "PERL/USDT",
    "SKY/BTC",
    "PNT/USDT",
    "MDA/BTC",
    "MITH/USDT",
    "QKC/BTC",
    "WRX/USDT",
    "LSK/BTC",
    "THETA/BNB",
    "STMX/BNB",
    "SNM/BTC",
    "NKN/BNB",
    "ETC/BTC",
    "WAN/BNB",
    "ANKR/BTC",
    "IQ/BNB",
    "RVN/BNB",
    "VET/USDT",
    "ZEC/BNB",
    "BUSD/USDT",
    "BAND/BNB",
    "PERL/BNB",
    "BTCUP/USDT",
    "CTXC/USDT",
    "XLM/USDT",
    "MANA/BTC",
    "CHR/BNB",
    "COTI/BNB",
    "NANO/USDT",
    "STEEM/BNB",
    "HOT/USDT",
    "HOT/BNB",
    "ONT/BNB",
    "OMG/USDT",
    "LRC/BTC",
    "FUN/BTC",
    "ETC/BNB",
    "DATA/BTC",
    "ARPA/BTC",
    "ARPA/BNB",
    "MDT/USDT",
    "OST/BTC",
    "NXS/BTC",
    "ADA/USDT",
    "POLY/BTC",
    "NKN/USDT",
    "POE/BTC",
    "WAVES/USDT",
    "WAN/BTC",
    "CELR/BNB",
    "HIVE/BNB",
    "LEND/USDT",
    "IOTX/BTC",
    "ZIL/BNB",
    "KAVA/USDT",
    "LSK/USDT",
    "XMR/BTC",
    "RLC/BNB",
    "CND/BTC",
    "FTT/USDT",
    "IOST/USDT",
    "REN/BTC",
    "DOCK/BTC",
    "KNC/BTC",
    "PHB/BTC",
    "SYS/BTC",
    "STX/BTC",
    "RLC/USDT",
    "DOCK/USDT",
    "IOTA/BTC",
    "ENG/BTC",
    "TROY/BNB",
    "DLT/BTC",
    "CHZ/BTC",
    "ANKR/USDT",
    "ARDR/USDT",
    "XMR/USDT",
    "VIA/BTC",
    "CMT/BTC",
    "AST/BTC",
    "APPC/BTC",
    "TFUEL/BTC",
    "HC/USDT",
    "LOOM/BTC",
    "DOGE/USDT",
    "AION/BNB",
    "HIVE/BTC",
    "CTSI/USDT",
    "NEO/BTC",
    "BAT/USDT",
    "XTZ/BTC",
    "BAT/BTC",
    "THETA/USDT",
    "CHZ/USDT",
    "VET/BTC",
    "BAND/BTC",
    "ELF/BTC",
    "GO/BTC",
    "NKN/BTC",
    "MITH/BTC",
    "PIVX/BTC",
    "ERD/USDT",
    "MATIC/BTC",
    "ICX/BNB",
    "VIBE/BTC",
    "RDN/BTC",
    "QSP/BTC",
    "ARN/BTC",
    "WTC/USDT",
    "BCH/BTC",
    "XTZ/BNB",
    "TFUEL/USDT",
    "WPR/BTC",
    "MATIC/USDT",
    "VITE/USDT",
    "TOMO/USDT",
    "CELR/USDT",
    "HBAR/BNB",
    "NAV/BTC",
    "DCR/BTC",
    "DATA/USDT",
    "QLC/BTC",
    "NEO/BNB",
    "ARPA/USDT",
    "GNT/BTC",
    "XEM/BTC",
    "NULS/BTC",
    "BRD/BTC",
    "ZEC/USDT",
    "HC/BTC",
    "BTG/BTC",
    "IOTA/USDT",
    "HOT/BTC",
    "BQX/BTC",
    "STORJ/BTC",
    "CHZ/BNB",
    "ATOM/BNB",
    "BAT/BNB",
    "TCT/BTC",
    "BRD/BNB",
    "COS/BTC",
    "MFT/USDT",
    "KMD/BTC",
    "REP/BTC",
    "ALGO/USDT",
    "LTO/USDT",
    "REQ/BTC",
    "AE/BTC",
    "TOMO/BTC",
    "CELR/BTC",
    "ARDR/BTC",
    "XRP/BNB",
    "BLZ/BTC",
    "ERD/BTC",
    "NPXS/USDT",
    "ONE/USDT",
    "ONE/BNB",
    "ZRX/BNB",
    "LINK/BTC",
    "COTI/BTC",
    "WTC/BNB",
    "XRP/USDT",
    "RLC/BTC",
    "XZC/BTC",
    "NULS/USDT",
    "RCN/BTC",
    "KEY/USDT",
    "BNB/BTC",
    "WABI/BTC",
    "ICX/BTC",
    "STMX/USDT",
    "CVC/USDT",
    "FUEL/BTC",
    "BNT/BTC",
    "PPT/BTC",
    "BTCDOWN/USDT",
    "TUSD/USDT",
    "XLM/BTC",
    "TNT/BTC",
    "KAVA/BTC",
    "ICX/USDT",
    "GXS/BTC",
    "ERD/BNB",
    "STPT/USDT",
    "BLZ/BNB",
    "CTSI/BTC",
    "CTXC/BTC",
    "FTM/USDT",
    "BCPT/BTC",
    "HBAR/USDT",
    "GTO/BTC",
    "IOST/BNB",
    "BEAM/BTC",
    "STX/BNB",
    "STRAT/USDT",
    "XLM/BNB",
    "VIB/BTC",
    "IOST/BTC",
    "ADA/BNB",
    "ADX/BTC",
    "QTUM/USDT",
    "INS/BTC",
    "CHR/BTC",
    "FTT/BTC",
    "AION/BTC",
    "XMR/BNB",
    "BCH/BNB",
    "MTL/BTC",
    "BAND/USDT",
    "EOS/BNB",
    "ZIL/USDT",
    "DUSK/USDT",
    "ONT/USDT",
    "SOL/BNB",
    "GTO/USDT",
    "ALGO/BNB",
    "FTM/BNB",
    "BTS/USDT",
    "DASH/BNB",
    "HIVE/USDT",
    "DREP/USDT",
    "STMX/BTC",
    "DGB/BNB",
    "GXS/USDT",
    "ETH/USDT",
    "DASH/BTC",
    "COS/USDT",
    "STPT/BTC",
    "STX/USDT",
    "VITE/BTC",
    "MDT/BTC",
    "ANKR/BNB",
    "GRS/BTC",
    "RVN/USDT",
    "GAS/BTC",
    "WRX/BNB",
]

for i in range(2, 60):
    print("day =", i)
    temp_func(i)

ticker_list = [
    "WTC/BNB",
    "GTO/ETH",
    "FTM/BNB",
    "THETA/ETH",
    "XLM/BNB",
    "WIN/USDT",
    "ATOM/USDT",
    "NULS/USDT",
    "XZC/ETH",
    "HC/USDT",
    "KEY/ETH",
    "IOTA/ETH",
    "ZEC/ETH",
    "ADA/ETH",
    "ZEN/ETH",
    "POWR/ETH",
    "LOOM/ETH",
    "TROY/USDT",
    "MFT/ETH",
    "ZIL/USDT",
    "TOMO/BNB",
    "BNB/ETH",
    "ICX/USDT",
    "XRP/USDT",
    "DOCK/USDT",
    "BTCUP/USDT",
    "BQX/ETH",
    "ETC/ETH",
    "WAVES/ETH",
    "NPXS/ETH",
    "HOT/ETH",
    "LEND/USDT",
    "HOT/USDT",
    "ZRX/BNB",
    "WAN/ETH",
    "ALGO/BNB",
    "WRX/BNB",
    "MDT/USDT",
    "ADA/USDT",
    "NULS/ETH",
    "BLZ/ETH",
    "XMR/ETH",
    "COS/BNB",
    "IQ/BNB",
    "PERL/BNB",
    "NPXS/USDT",
    "MCO/USDT",
    "OMG/USDT",
    "FET/USDT",
    "LEND/ETH",
    "EUR/USDT",
    "LTC/ETH",
    "WAVES/USDT",
    "ICX/BNB",
    "NKN/USDT",
    "ZEC/BNB",
    "KEY/USDT",
    "LRC/ETH",
    "LSK/ETH",
    "WIN/BNB",
    "PERL/USDT",
    "ZIL/ETH",
    "MANA/ETH",
    "NEO/BNB",
    "XTZ/BNB",
    "FUN/USDT",
    "THETA/BNB",
    "BNT/ETH",
    "GNT/ETH",
    "TROY/BNB",
    "WTC/USDT",
    "MBL/BNB",
    "STEEM/ETH",
    "RLC/ETH",
    "AION/ETH",
    "DOCK/ETH",
    "CHZ/BNB",
    "CELR/BNB",
    "STX/BNB",
    "LRC/USDT",
    "XRP/ETH",
    "MITH/BNB",
    "BTS/USDT",
    "PAX/USDT",
    "BTT/USDT",
    "ARPA/USDT",
    "BAT/ETH",
    "CTXC/USDT",
    "BTCDOWN/USDT",
    "OST/ETH",
    "DATA/USDT",
    "HIVE/BNB",
    "KAVA/BNB",
    "MCO/ETH",
    "GTO/USDT",
    "ETC/BNB",
    "KAVA/USDT",
    "RLC/USDT",
    "NANO/USDT",
    "ELF/ETH",
    "MFT/USDT",
    "CTSI/USDT",
    "FTT/USDT",
    "SNT/ETH",
    "KNC/ETH",
    "MBL/USDT",
    "ZRX/USDT",
    "XTZ/USDT",
    "BRD/BNB",
    "QKC/ETH",
    "DUSK/USDT",
    "EOS/BNB",
    "STMX/BNB",
    "HBAR/USDT",
    "GXS/ETH",
    "NEO/ETH",
    "QSP/ETH",
    "ADX/ETH",
    "MFT/BNB",
    "MATIC/BNB",
    "NEBL/BNB",
    "REN/USDT",
    "ARDR/USDT",
    "VITE/USDT",
    "XEM/ETH",
    "MDT/BNB",
    "ANKR/BNB",
    "HIVE/USDT",
    "BTT/BNB",
    "ONT/ETH",
    "IOTX/ETH",
    "VET/ETH",
    "ICX/ETH",
    "ARPA/BNB",
    "DREP/USDT",
    "REP/ETH",
    "ZEN/BNB",
    "TUSD/USDT",
    "IOST/ETH",
    "USDC/USDT",
    "EOS/USDT",
    "LSK/USDT",
    "ONT/USDT",
    "XZC/USDT",
    "OGN/BNB",
    "LINK/USDT",
    "DASH/ETH",
    "ARN/ETH",
    "SC/BNB",
    "CTSI/BNB",
    "ETC/USDT",
    "BAT/USDT",
    "SOL/BNB",
    "ENJ/BNB",
    "LTC/USDT",
    "REP/USDT",
    "ONE/BNB",
    "CHR/BNB",
    "BUSD/USDT",
    "MITH/USDT",
    "STORJ/ETH",
    "OGN/USDT",
    "STMX/ETH",
    "XMR/BNB",
    "TRX/USDT",
    "XLM/USDT",
    "ADA/BNB",
    "COTI/BNB",
    "HBAR/BNB",
    "BLZ/BNB",
    "ENJ/USDT",
    "FUN/ETH",
    "NAS/ETH",
    "ONE/USDT",
    "BAT/BNB",
    "CELR/USDT",
    "ZIL/BNB",
    "KNC/USDT",
    "BNB/USDT",
    "TOMO/USDT",
    "ETH/USDT",
    "MATIC/USDT",
    "FTM/USDT",
    "HOT/BNB",
    "IOTA/USDT",
    "COTI/USDT",
    "CMT/ETH",
    "BAND/BNB",
    "DOGE/USDT",
    "AE/ETH",
    "NCASH/ETH",
    "STMX/USDT",
    "GXS/USDT",
    "COS/USDT",
    "VIB/ETH",
    "ERD/BNB",
    "BCH/BNB",
    "BNT/USDT",
    "DASH/USDT",
    "QLC/ETH",
    "BEAM/USDT",
    "EVX/ETH",
    "VET/BNB",
    "NKN/BNB",
    "WAN/USDT",
    "ANKR/USDT",
    "OMG/ETH",
    "STX/USDT",
    "BAND/USDT",
    "NANO/ETH",
    "ENG/ETH",
    "TNT/ETH",
    "ALGO/USDT",
    "DENT/USDT",
    "TCT/USDT",
    "THETA/USDT",
    "NEO/USDT",
    "LINK/ETH",
    "NEBL/ETH",
    "WABI/BNB",
    "LTC/BNB",
    "TFUEL/USDT",
    "ZEC/USDT",
    "KMD/ETH",
    "RLC/BNB",
    "FET/BNB",
    "WAVES/BNB",
    "AION/BNB",
    "IOST/USDT",
    "RVN/USDT",
    "CHR/USDT",
    "ENJ/ETH",
    "BTC/USDT",
    "IOTX/USDT",
    "AION/USDT",
    "CDT/ETH",
    "CVC/ETH",
    "MTL/ETH",
    "COCOS/USDT",
    "COCOS/BNB",
    "XZC/BNB",
    "XRP/BNB",
    "FTT/BNB",
    "QTUM/USDT",
    "XLM/ETH",
    "USDS/USDT",
    "CVC/USDT",
    "STPT/USDT",
    "WTC/ETH",
    "TRX/ETH",
    "DATA/ETH",
    "IOTA/BNB",
    "ERD/USDT",
    "WRX/USDT",
    "STEEM/BNB",
    "STRAT/USDT",
    "CHZ/USDT",
    "BCH/USDT",
    "ATOM/BNB",
    "XVG/ETH",
    "ZRX/ETH",
    "XMR/USDT",
    "EOS/ETH",
    "SC/ETH",
    "VET/USDT",
    "DENT/ETH",
    "PIVX/ETH",
    "BRD/ETH",
    "RVN/BNB",
    "ONT/BNB",
    "TRX/BNB",
    "DASH/BNB",
    "IOST/BNB",
    "QTUM/ETH",
    "LTO/USDT",
    "ONG/USDT",
    "WAN/BNB",
    "MTL/USDT",
    "STRAT/ETH",
]

for j in range(2, 60):
    print("day =", j)
    temp_func(j)


"""
종목 풀은 USDT 고정

1번 : 전일 IBS가 가장 낮은 3개 금일 시가 매수 후 종가 청산

2번 : 전일 IBS가 가장 낮은 3개 금일 시가 매도 후 종가 청산

3번 : 전일 IBS가 가장 높은 3개 금일 시가 매수 후 종가 청산

4번 : 전일 IBS가 가장 높은 3개 금일 시가 매도 후 종가 청산

5번 : 선물 버전의 IBS 3개 (1)low_buy, (2)low_sell, (3)high_buy, (4)high_sell

6번 수익 계산, 조합에 의한 수익 계산 1번 3번 조합, 5번에서 (1),(3) / (1),(4) / (2),(3) / (2),(4)

6-1 : high_low_buy가 가장 안정적인 성과를 보였다. 정말 그런건가?
    선물 시장에서 high_buy2개, low_buy2개로 하고 포지션 사이징을 아주 작게 가져간다면 가능

7번 : S2전략의 변형, S1.5는 안되는가?

9번 : 고가가 R2인 종목을 당일에 들어가지 말고 종가가 R2인 종목을 다음날에 들어가보자 

10번 : 9번 R2 -> R3

11 : 10 R3 -> S2 sell

12 : 11 S2 -> S3

http://blog.naver.com/PostView.nhn?blogId=newsystock&logNo=221571325215&parentCategoryNo=&categoryNo=31&viewDate=&isShowPopularPosts=false&from=postView


"""
