import ccxt
import time
from pprint import pprint
import datetime
import random


def get_tickers(base):
    # base = '/USDT' or '/BNB' or '/BTC' or ...
    All_ticker = binance.fetch_tickers().keys()
    tickers = [s for s in All_ticker if base in s]
    result = []
    for i, item in enumerate(tickers):
        ohlcv = binance.fetch_order_book(item)
        if len(ohlcv["bids"]) != 0:
            result.append(item)
    return result


def get_time(temp):
    now = temp
    YYYY = str(now.year)
    MM = str(now.month)
    DD = str(now.day)
    hh = str(now.hour)
    mm = str(now.minute)

    if len(MM) != 2:
        MM = "0" + MM
    if len(DD) != 2:
        DD = "0" + DD
    if len(hh) != 2:
        hh = "0" + hh
    if len(mm) != 2:
        mm = "0" + mm

    return YYYY + MM + DD, hh + mm


"""
binance = ccxt.binance({
    'apiKey': '3pFJ5lblk8ff8brlz2plOG2o',
    'secret': 'KKFk0a-YvtW8aEcS33HbQlxJ63rHpdA95D7IWNALSOTVraB1',
    'enableRateLimit': False,
    'RateLimit' : 10000
})
binance.load_markets()
"""

binance = ccxt.binance(
    {
        "options": {"defaultType": "future"},
        "timeout": 30000,
        "apiKey": "f6LEy0POPdaukqwlrnC4KvJbGWkcXRfVmKbsPmFAaPlyL2Rytswf7ilTa3kAjnQh",
        "secret": "sLvrd7ZT6c49yZVlnFRhPvJcIg8z39S6dVwZcIfPhFueA5BAy5UpTT3ZbVZg9zA2",
        "enableRateLimit": False,
    }
)
binance.load_markets()


time_frame = "1d"


# ticker_list = list(set(get_tickers('/ETH')) | set(get_tickers('/BNB')) | set(get_tickers('/USDT')) | set(get_tickers('/BTC')))

# ticker_list = ['WTC/BNB', 'GTO/ETH', 'FTM/BNB', 'THETA/ETH', 'XLM/BNB', 'WIN/USDT', 'ATOM/USDT', 'NULS/USDT', 'XZC/ETH', 'HC/USDT', 'KEY/ETH', 'IOTA/ETH', 'ZEC/ETH', 'ADA/ETH', 'ZEN/ETH', 'POWR/ETH', 'LOOM/ETH', 'TROY/USDT', 'MFT/ETH', 'ZIL/USDT', 'TOMO/BNB', 'BNB/ETH', 'ICX/USDT', 'XRP/USDT', 'DOCK/USDT', 'BTCUP/USDT', 'BQX/ETH', 'ETC/ETH', 'WAVES/ETH', 'NPXS/ETH', 'HOT/ETH', 'LEND/USDT', 'HOT/USDT', 'ZRX/BNB', 'WAN/ETH', 'ALGO/BNB', 'WRX/BNB', 'MDT/USDT', 'ADA/USDT', 'NULS/ETH', 'BLZ/ETH', 'XMR/ETH', 'COS/BNB', 'IQ/BNB', 'PERL/BNB', 'NPXS/USDT', 'MCO/USDT', 'OMG/USDT', 'FET/USDT', 'LEND/ETH', 'EUR/USDT', 'LTC/ETH', 'WAVES/USDT', 'ICX/BNB', 'NKN/USDT', 'ZEC/BNB', 'KEY/USDT', 'LRC/ETH', 'LSK/ETH', 'WIN/BNB', 'PERL/USDT', 'ZIL/ETH', 'MANA/ETH', 'NEO/BNB', 'XTZ/BNB', 'FUN/USDT', 'THETA/BNB', 'BNT/ETH', 'GNT/ETH', 'TROY/BNB', 'WTC/USDT', 'MBL/BNB', 'STEEM/ETH', 'RLC/ETH', 'AION/ETH', 'DOCK/ETH', 'CHZ/BNB', 'CELR/BNB', 'STX/BNB', 'LRC/USDT', 'XRP/ETH', 'MITH/BNB', 'BTS/USDT', 'PAX/USDT', 'BTT/USDT', 'ARPA/USDT', 'BAT/ETH', 'CTXC/USDT', 'BTCDOWN/USDT', 'OST/ETH', 'DATA/USDT', 'HIVE/BNB', 'KAVA/BNB', 'MCO/ETH', 'GTO/USDT', 'ETC/BNB', 'KAVA/USDT', 'RLC/USDT', 'NANO/USDT', 'ELF/ETH', 'MFT/USDT', 'CTSI/USDT', 'FTT/USDT', 'SNT/ETH', 'KNC/ETH', 'MBL/USDT', 'ZRX/USDT', 'XTZ/USDT', 'BRD/BNB', 'QKC/ETH', 'DUSK/USDT', 'EOS/BNB', 'STMX/BNB', 'HBAR/USDT', 'GXS/ETH', 'NEO/ETH', 'QSP/ETH', 'ADX/ETH', 'MFT/BNB', 'MATIC/BNB', 'NEBL/BNB', 'REN/USDT', 'ARDR/USDT', 'VITE/USDT', 'XEM/ETH', 'MDT/BNB', 'ANKR/BNB', 'HIVE/USDT', 'BTT/BNB', 'ONT/ETH', 'IOTX/ETH', 'VET/ETH', 'ICX/ETH', 'ARPA/BNB', 'DREP/USDT', 'REP/ETH', 'ZEN/BNB', 'TUSD/USDT', 'IOST/ETH', 'USDC/USDT', 'EOS/USDT', 'LSK/USDT', 'ONT/USDT', 'XZC/USDT', 'OGN/BNB', 'LINK/USDT', 'DASH/ETH', 'ARN/ETH', 'SC/BNB', 'CTSI/BNB', 'ETC/USDT', 'BAT/USDT', 'SOL/BNB', 'ENJ/BNB', 'LTC/USDT', 'REP/USDT', 'ONE/BNB', 'CHR/BNB', 'BUSD/USDT', 'MITH/USDT', 'STORJ/ETH', 'OGN/USDT', 'STMX/ETH', 'XMR/BNB', 'TRX/USDT', 'XLM/USDT', 'ADA/BNB', 'COTI/BNB', 'HBAR/BNB', 'BLZ/BNB', 'ENJ/USDT', 'FUN/ETH', 'NAS/ETH', 'ONE/USDT', 'BAT/BNB', 'CELR/USDT', 'ZIL/BNB', 'KNC/USDT', 'BNB/USDT', 'TOMO/USDT', 'ETH/USDT', 'MATIC/USDT', 'FTM/USDT', 'HOT/BNB', 'IOTA/USDT', 'COTI/USDT', 'CMT/ETH', 'BAND/BNB', 'DOGE/USDT', 'AE/ETH', 'NCASH/ETH', 'STMX/USDT', 'GXS/USDT', 'COS/USDT', 'VIB/ETH', 'ERD/BNB', 'BCH/BNB', 'BNT/USDT', 'DASH/USDT', 'QLC/ETH', 'BEAM/USDT', 'EVX/ETH', 'VET/BNB', 'NKN/BNB', 'WAN/USDT', 'ANKR/USDT', 'OMG/ETH', 'STX/USDT', 'BAND/USDT', 'NANO/ETH', 'ENG/ETH', 'TNT/ETH', 'ALGO/USDT', 'DENT/USDT', 'TCT/USDT', 'THETA/USDT', 'NEO/USDT', 'LINK/ETH', 'NEBL/ETH', 'WABI/BNB', 'LTC/BNB', 'TFUEL/USDT', 'ZEC/USDT', 'KMD/ETH', 'RLC/BNB', 'FET/BNB', 'WAVES/BNB', 'AION/BNB', 'IOST/USDT', 'RVN/USDT', 'CHR/USDT', 'ENJ/ETH', 'BTC/USDT', 'IOTX/USDT', 'AION/USDT', 'CDT/ETH', 'CVC/ETH', 'MTL/ETH', 'COCOS/USDT', 'COCOS/BNB', 'XZC/BNB', 'XRP/BNB', 'FTT/BNB', 'QTUM/USDT', 'XLM/ETH', 'USDS/USDT', 'CVC/USDT', 'STPT/USDT', 'WTC/ETH', 'TRX/ETH', 'DATA/ETH', 'IOTA/BNB', 'ERD/USDT', 'WRX/USDT', 'STEEM/BNB', 'STRAT/USDT', 'CHZ/USDT', 'BCH/USDT', 'ATOM/BNB', 'XVG/ETH', 'ZRX/ETH', 'XMR/USDT', 'EOS/ETH', 'SC/ETH', 'VET/USDT', 'DENT/ETH', 'PIVX/ETH', 'BRD/ETH', 'RVN/BNB', 'ONT/BNB', 'TRX/BNB', 'DASH/BNB', 'IOST/BNB', 'QTUM/ETH', 'LTO/USDT', 'ONG/USDT', 'WAN/BNB', 'MTL/USDT', 'STRAT/ETH']

# ticker_list = ['NULS/BTC', 'BTS/USDT', 'ENG/BTC', 'BAT/ETH', 'POWR/ETH', 'MITH/BTC', 'XVG/BTC', 'BUSD/USDT', 'ANKR/USDT', 'THETA/BNB', 'THETA/USDT', 'IOTA/BNB', 'MTL/ETH', 'BAT/BTC', 'KEY/USDT', 'ZIL/BNB', 'OST/ETH', 'MTL/BTC', 'SKY/BTC', 'ZRX/ETH', 'ZEC/BNB', 'WRX/USDT', 'CHR/BTC', 'NAS/ETH', 'EOS/USDT', 'ETC/USDT', 'HC/BTC', 'BRD/BTC', 'GXS/BTC', 'EVX/BTC', 'XTZ/BNB', 'NEO/ETH', 'ONG/USDT', 'STRAT/USDT', 'CMT/BTC', 'QTUM/USDT', 'DNT/BTC', 'MCO/BTC', 'LUN/BTC', 'XZC/BTC', 'LEND/BTC', 'BRD/ETH', 'MFT/ETH', 'GTO/USDT', 'DATA/USDT', 'KNC/BTC', 'TNT/ETH', 'MATIC/USDT', 'DOGE/USDT', 'FTM/BNB', 'PERL/BNB', 'MATIC/BNB', 'WAVES/BNB', 'VIA/BTC', 'QLC/ETH', 'MTL/USDT', 'LTC/ETH', 'HOT/USDT', 'MBL/USDT', 'WAN/BTC', 'DUSK/USDT', 'GAS/BTC', 'ERD/BNB', 'AMB/BTC', 'MDT/BNB', 'HC/USDT', 'FTT/USDT', 'IOTX/BTC', 'FET/USDT', 'XLM/USDT', 'BTT/BNB', 'NAV/BTC', 'WTC/USDT', 'GTO/ETH', 'BCH/BNB', 'FUN/BTC', 'ONT/ETH', 'ARPA/USDT', 'COTI/USDT', 'WAVES/ETH', 'ZEN/BNB', 'CHZ/USDT', 'VIB/ETH', 'VITE/USDT', 'WAN/USDT', 'KMD/BTC', 'WIN/USDT', 'ONT/BTC', 'HIVE/BNB', 'MDT/USDT', 'BCD/BTC', 'NCASH/ETH', 'AE/ETH', 'IOTA/BTC', 'XEM/ETH', 'XTZ/BTC', 'REP/ETH', 'IOTX/USDT', 'ENG/ETH', 'ARN/BTC', 'CVC/ETH', 'DATA/ETH', 'WAVES/USDT', 'USDS/USDT', 'YOYOW/BTC', 'STEEM/ETH', 'KNC/ETH', 'ZEN/BTC', 'XEM/BTC', 'SYS/BTC', 'FTT/BNB', 'HBAR/BNB', 'OST/BTC', 'NULS/ETH', 'THETA/ETH', 'COS/USDT', 'FUN/USDT', 'RVN/BTC', 'GNT/BTC', 'LRC/USDT', 'MFT/BNB', 'AGI/BTC', 'WAN/ETH', 'COCOS/BNB', 'TUSD/USDT', 'STMX/ETH', 'NKN/USDT', 'XRP/BNB', 'LSK/ETH', 'WPR/BTC', 'POWR/BTC', 'ATOM/BTC', 'XRP/BTC', 'ADA/BNB', 'TROY/BTC', 'ZEC/BTC', 'XMR/ETH', 'ZIL/BTC', 'XVG/ETH', 'IOTX/ETH', 'ONE/BTC', 'BCH/BTC', 'FTM/BTC', 'DASH/ETH', 'DREP/BTC', 'VET/BNB', 'STPT/BTC', 'RLC/BNB', 'ARDR/BTC', 'MANA/ETH', 'OMG/ETH', 'WIN/BNB', 'XRP/ETH', 'STX/USDT', 'DOCK/USDT', 'CTXC/USDT', 'MBL/BTC', 'PERL/BTC', 'CTSI/BNB', 'BAT/BNB', 'STPT/USDT', 'NEBL/BNB', 'CVC/BTC', 'LTC/USDT', 'CHR/BNB', 'TOMO/BNB', 'CDT/BTC', 'NEBL/ETH', 'WAN/BNB', 'BEAM/BTC', 'ETH/BTC', 'DASH/BNB', 'SNGLS/BTC', 'ONE/BNB', 'WABI/BNB', 'TCT/BTC', 'ZIL/ETH', 'ETC/BTC', 'XMR/BTC', 'TOMO/BTC', 'FTT/BTC', 'MCO/ETH', 'MFT/USDT', 'VET/BTC', 'KMD/ETH', 'STORJ/BTC', 'XMR/USDT', 'BAND/USDT', 'LINK/BTC', 'FUEL/BTC', 'ALGO/BNB', 'CDT/ETH', 'RVN/USDT', 'BTCDOWN/USDT', 'ZRX/BTC', 'AION/BTC', 'NPXS/USDT', 'OGN/BTC', 'ENJ/ETH', 'LTC/BNB', 'QKC/ETH', 'FTM/USDT', 'BAND/BNB', 'LEND/USDT', 'DUSK/BTC', 'ERD/USDT', 'AION/BNB', 'IOST/BNB', 'ADA/USDT', 'BEAM/USDT', 'ERD/BTC', 'NEO/BNB', 'IOTA/ETH', 'LTO/BTC', 'XRP/USDT', 'DOGE/BTC', 'NANO/ETH', 'ZIL/USDT', 'OAX/BTC', 'NKN/BNB', 'TROY/BNB', 'TFUEL/BTC', 'TFUEL/USDT', 'LTC/BTC', 'ANKR/BNB', 'ARK/BTC', 'NANO/BTC', 'ATOM/BNB', 'BNT/ETH', 'USDC/USDT', 'CELR/BTC', 'HOT/BNB', 'NEO/USDT', 'ARN/ETH', 'BCH/USDT', 'XZC/BNB', 'LRC/BTC', 'KAVA/BNB', 'POLY/BTC', 'HIVE/USDT', 'AION/ETH', 'WTC/BTC', 'BRD/BNB', 'ETH/USDT', 'SOL/BNB', 'LOOM/ETH', 'COS/BTC', 'ONE/USDT', 'CELR/BNB', 'WRX/BTC', 'SNT/ETH', 'LOOM/BTC', 'ARPA/BTC', 'BTCUP/USDT', 'POA/BTC', 'OGN/BNB', 'LSK/USDT', 'TRX/USDT', 'EOS/ETH', 'QKC/BTC', 'ENJ/USDT', 'MITH/USDT', 'NULS/USDT', 'POE/BTC', 'NAS/BTC', 'ELF/ETH', 'GTO/BTC', 'COTI/BNB', 'HIVE/BTC', 'XZC/ETH', 'MDT/BTC', 'FET/BNB', 'GXS/ETH', 'EOS/BNB', 'IOST/USDT', 'GXS/USDT', 'VITE/BTC', 'BAT/USDT', 'STX/BTC', 'ALGO/USDT', 'LEND/ETH', 'COS/BNB', 'ZEN/ETH', 'ATOM/USDT', 'RLC/BTC', 'CTSI/BTC', 'XTZ/USDT', 'ZRX/USDT', 'ICX/BTC', 'TRX/BTC', 'CHZ/BTC', 'BTS/BTC', 'TNB/BTC', 'KEY/ETH', 'DENT/USDT', 'NANO/USDT', 'CMT/ETH', 'CHZ/BNB', 'NEO/BTC', 'MATIC/BTC', 'OMG/USDT', 'LRC/ETH', 'WABI/BTC', 'WTC/ETH', 'KAVA/USDT', 'DATA/BTC', 'WAVES/BTC', 'ADX/ETH', 'BTG/BTC', 'QTUM/ETH', 'STRAT/BTC', 'XMR/BNB', 'ICX/ETH', 'PIVX/BTC', 'LINK/ETH', 'GVT/BTC', 'NXS/BTC', 'NPXS/ETH', 'VET/USDT', 'XZC/USDT', 'STMX/USDT', 'AE/BTC', 'APPC/BTC', 'PAX/USDT', 'BTT/USDT', 'CVC/USDT', 'SC/ETH', 'MBL/BNB', 'STRAT/ETH', 'KNC/USDT', 'ONT/BNB', 'RLC/USDT', 'DOCK/BTC', 'ALGO/BTC', 'BLZ/BNB', 'CTXC/BTC', 'GO/BTC', 'IOST/ETH', 'BNT/USDT', 'IOTA/USDT', 'BQX/ETH', 'MTH/BTC', 'ONG/BTC', 'REN/USDT', 'ENJ/BNB', 'LTO/USDT', 'WTC/BNB', 'BAND/BTC', 'ARPA/BNB', 'CTSI/USDT', 'CND/BTC', 'BNB/USDT', 'KAVA/BTC', 'ADA/BTC', 'PERL/USDT', 'ICX/USDT', 'HOT/ETH', 'MANA/BTC', 'ANKR/BTC', 'DREP/USDT', 'LSK/BTC', 'INS/BTC', 'BLZ/ETH', 'TOMO/USDT', 'REP/USDT', 'STEEM/BNB', 'NEBL/BTC', 'ZEC/USDT', 'STX/BNB', 'ZEC/ETH', 'VIBE/BTC', 'ONT/USDT', 'PHB/BTC', 'REN/BTC', 'AION/USDT', 'HOT/BTC', 'RLC/ETH', 'CELR/USDT', 'BLZ/BTC', 'COCOS/USDT', 'EUR/USDT', 'BQX/BTC', 'RDN/BTC', 'TRX/BNB', 'HBAR/BTC', 'STORJ/ETH', 'THETA/BTC', 'PIVX/ETH', 'BNB/BTC', 'ENJ/BTC', 'SNT/BTC', 'IQ/BNB', 'ETC/BNB', 'DASH/BTC', 'SC/BTC', 'REP/BTC', 'CHR/USDT', 'ETC/ETH', 'GNT/ETH', 'FET/BTC', 'DENT/ETH', 'XLM/ETH', 'ARDR/USDT', 'QSP/BTC', 'TROY/USDT', 'SOL/BTC', 'OGN/USDT', 'BCPT/BTC', 'ZRX/BNB', 'SC/BNB', 'REQ/BTC', 'BCN/ETH', 'RCN/BTC', 'TCT/USDT', 'LINK/USDT', 'STMX/BTC', 'QSP/ETH', 'XLM/BNB', 'DLT/BTC', 'ADA/ETH', 'STMX/BNB', 'WRX/BNB', 'IOST/BTC', 'COTI/BTC', 'QLC/BTC', 'TNT/BTC', 'XLM/BTC', 'EOS/BTC', 'GRS/BTC', 'SNM/BTC', 'ADX/BTC', 'DASH/USDT', 'HBAR/USDT', 'ELF/BTC', 'BNB/ETH', 'TRX/ETH', 'QTUM/BTC', 'VET/ETH', 'MCO/USDT', 'ICX/BNB', 'PPT/BTC', 'DOCK/ETH', 'MITH/BNB', 'BTC/USDT', 'OMG/BTC', 'VIB/BTC', 'EVX/ETH', 'NKN/BTC', 'STEEM/BTC', 'FUN/ETH', 'DCR/BTC', 'BNT/BTC', 'MDA/BTC', 'AST/BTC', 'RVN/BNB']

# ticker_list = ['ENJ/BNB', 'ATOM/USDT', 'LTC/BNB', 'BNB/USDT', 'FET/BTC', 'STEEM/BTC', 'OMG/BTC', 'EOS/BTC', 'RVN/BTC', 'BTC/USDT', 'TROY/USDT', 'MBL/USDT', 'COS/BNB', 'CHR/USDT', 'MTH/BTC', 'EVX/BTC', 'LUN/BTC', 'MBL/BNB', 'FTM/BTC', 'DENT/USDT', 'ZRX/BTC', 'ZEN/BTC', 'FET/BNB', 'DNT/BTC', 'MCO/BTC', 'LRC/USDT', 'DOGE/BTC', 'MFT/BNB', 'PAX/USDT', 'PNT/BTC', 'SNGLS/BTC', 'LTO/BTC', 'ETC/USDT', 'COCOS/USDT', 'FTT/BNB', 'AION/USDT', 'PERL/BTC', 'IOTA/BNB', 'ATOM/BTC', 'MITH/BNB', 'BCD/BTC', 'GVT/BTC', 'TRX/BNB', 'TNB/BTC', 'SOL/BTC', 'TRX/BTC', 'CDT/BTC', 'ZIL/BTC', 'WIN/USDT', 'NAS/BTC', 'NEBL/BNB', 'OGN/USDT', 'ZRX/USDT', 'WAVES/BNB', 'BNT/USDT', 'NANO/BTC', 'ONG/BTC', 'ADA/BTC', 'WAN/USDT', 'AGI/BTC', 'DREP/BTC', 'WRX/BTC', 'DGB/BTC', 'EOS/USDT', 'NEO/USDT', 'XZC/USDT', 'MTL/USDT', 'FUN/USDT', 'KNC/USDT', 'COCOS/BNB', 'WIN/BNB', 'HBAR/BTC', 'TOMO/BNB', 'REP/USDT', 'ARK/BTC', 'COTI/USDT', 'WABI/BNB', 'ZEC/BTC', 'TROY/BTC', 'KAVA/BNB', 'MBL/BTC', 'XTZ/USDT', 'MDT/BNB', 'ZEN/BNB', 'ALGO/BTC', 'LEND/BTC', 'ONE/BTC', 'TCT/USDT', 'CTSI/BNB', 'DASH/USDT', 'CVC/BTC', 'MATIC/BNB', 'OGN/BTC', 'OGN/BNB', 'ENJ/USDT', 'POA/BTC', 'TRX/USDT', 'SNT/BTC', 'USDC/USDT', 'QTUM/BTC', 'SC/BNB', 'ENJ/BTC', 'BCH/USDT', 'XZC/BNB', 'FET/USDT', 'REN/USDT', 'NEBL/BTC', 'MCO/USDT', 'ONG/USDT', 'AMB/BTC', 'POWR/BTC', 'STRAT/BTC', 'WTC/BTC', 'IOTX/USDT', 'WAVES/BTC', 'BEAM/USDT', 'ETH/BTC', 'DUSK/BTC', 'LTC/BTC', 'THETA/BTC', 'SC/BTC', 'EUR/USDT', 'LTC/USDT', 'BTT/USDT', 'LINK/USDT', 'XVG/BTC', 'BTS/BTC', 'OAX/BTC', 'BTT/BNB', 'VET/BNB', 'ONT/BTC', 'YOYOW/BTC', 'XRP/BTC', 'PERL/USDT', 'SKY/BTC', 'PNT/USDT', 'MDA/BTC', 'MITH/USDT', 'QKC/BTC', 'WRX/USDT', 'LSK/BTC', 'THETA/BNB', 'STMX/BNB', 'SNM/BTC', 'NKN/BNB', 'ETC/BTC', 'WAN/BNB', 'ANKR/BTC', 'IQ/BNB', 'RVN/BNB', 'VET/USDT', 'ZEC/BNB', 'BUSD/USDT', 'BAND/BNB', 'PERL/BNB', 'BTCUP/USDT', 'CTXC/USDT', 'XLM/USDT', 'MANA/BTC', 'CHR/BNB', 'COTI/BNB', 'NANO/USDT', 'STEEM/BNB', 'HOT/USDT', 'HOT/BNB', 'ONT/BNB', 'OMG/USDT', 'LRC/BTC', 'FUN/BTC', 'ETC/BNB', 'DATA/BTC', 'ARPA/BTC', 'ARPA/BNB', 'MDT/USDT', 'OST/BTC', 'NXS/BTC', 'ADA/USDT', 'POLY/BTC', 'NKN/USDT', 'POE/BTC', 'WAVES/USDT', 'WAN/BTC', 'CELR/BNB', 'HIVE/BNB', 'LEND/USDT', 'IOTX/BTC', 'ZIL/BNB', 'KAVA/USDT', 'LSK/USDT', 'XMR/BTC', 'RLC/BNB', 'CND/BTC', 'FTT/USDT', 'IOST/USDT', 'REN/BTC', 'DOCK/BTC', 'KNC/BTC', 'PHB/BTC', 'SYS/BTC', 'STX/BTC', 'RLC/USDT', 'DOCK/USDT', 'IOTA/BTC', 'ENG/BTC', 'TROY/BNB', 'DLT/BTC', 'CHZ/BTC', 'ANKR/USDT', 'ARDR/USDT', 'XMR/USDT', 'VIA/BTC', 'CMT/BTC', 'AST/BTC', 'APPC/BTC', 'TFUEL/BTC', 'HC/USDT', 'LOOM/BTC', 'DOGE/USDT', 'AION/BNB', 'HIVE/BTC', 'CTSI/USDT', 'NEO/BTC', 'BAT/USDT', 'XTZ/BTC', 'BAT/BTC', 'THETA/USDT', 'CHZ/USDT', 'VET/BTC', 'BAND/BTC', 'ELF/BTC', 'GO/BTC', 'NKN/BTC', 'MITH/BTC', 'PIVX/BTC', 'ERD/USDT', 'MATIC/BTC', 'ICX/BNB', 'VIBE/BTC', 'RDN/BTC', 'QSP/BTC', 'ARN/BTC', 'WTC/USDT', 'BCH/BTC', 'XTZ/BNB', 'TFUEL/USDT', 'WPR/BTC', 'MATIC/USDT', 'VITE/USDT', 'TOMO/USDT', 'CELR/USDT', 'HBAR/BNB', 'NAV/BTC', 'DCR/BTC', 'DATA/USDT', 'QLC/BTC', 'NEO/BNB', 'ARPA/USDT', 'GNT/BTC', 'XEM/BTC', 'NULS/BTC', 'BRD/BTC', 'ZEC/USDT', 'HC/BTC', 'BTG/BTC', 'IOTA/USDT', 'HOT/BTC', 'BQX/BTC', 'STORJ/BTC', 'CHZ/BNB', 'ATOM/BNB', 'BAT/BNB', 'TCT/BTC', 'BRD/BNB', 'COS/BTC', 'MFT/USDT', 'KMD/BTC', 'REP/BTC', 'ALGO/USDT', 'LTO/USDT', 'REQ/BTC', 'AE/BTC', 'TOMO/BTC', 'CELR/BTC', 'ARDR/BTC', 'XRP/BNB', 'BLZ/BTC', 'ERD/BTC', 'NPXS/USDT', 'ONE/USDT', 'ONE/BNB', 'ZRX/BNB', 'LINK/BTC', 'COTI/BTC', 'WTC/BNB', 'XRP/USDT', 'RLC/BTC', 'XZC/BTC', 'NULS/USDT', 'RCN/BTC', 'KEY/USDT', 'BNB/BTC', 'WABI/BTC', 'ICX/BTC', 'STMX/USDT', 'CVC/USDT', 'FUEL/BTC', 'BNT/BTC', 'PPT/BTC', 'BTCDOWN/USDT', 'TUSD/USDT', 'XLM/BTC', 'TNT/BTC', 'KAVA/BTC', 'ICX/USDT', 'GXS/BTC', 'ERD/BNB', 'STPT/USDT', 'BLZ/BNB', 'CTSI/BTC', 'CTXC/BTC', 'FTM/USDT', 'BCPT/BTC', 'HBAR/USDT', 'GTO/BTC', 'IOST/BNB', 'BEAM/BTC', 'STX/BNB', 'STRAT/USDT', 'XLM/BNB', 'VIB/BTC', 'IOST/BTC', 'ADA/BNB', 'ADX/BTC', 'QTUM/USDT', 'INS/BTC', 'CHR/BTC', 'FTT/BTC', 'AION/BTC', 'XMR/BNB', 'BCH/BNB', 'MTL/BTC', 'BAND/USDT', 'EOS/BNB', 'ZIL/USDT', 'DUSK/USDT', 'ONT/USDT', 'SOL/BNB', 'GTO/USDT', 'ALGO/BNB', 'FTM/BNB', 'BTS/USDT', 'DASH/BNB', 'HIVE/USDT', 'DREP/USDT', 'STMX/BTC', 'DGB/BNB', 'GXS/USDT', 'ETH/USDT', 'DASH/BTC', 'COS/USDT', 'STPT/BTC', 'STX/USDT', 'VITE/BTC', 'MDT/BTC', 'ANKR/BNB', 'GRS/BTC', 'RVN/USDT', 'GAS/BTC', 'WRX/BNB']


def temp_func(day, value):
    count = 0
    temp = []
    for i, item in enumerate(ticker_list):
        time.sleep(0.1)
        if count == 9999:
            return count, sum(temp), (sum(temp) / count)
        # try:
        ohlcv = binance.fetch_ohlcv(item, time_frame)
        PP = (
            ohlcv[-(day + 1)][2] + ohlcv[-(day + 1)][3] + (ohlcv[-(day + 1)][4] * 2)
        ) / 4
        S1_5 = value * PP - ohlcv[-(day + 1)][2]

        if ohlcv[-day][3] < S1_5:
            earning = round(-100 + ohlcv[-day][4] / S1_5 * 99.985, 5)
            # print(item, earning, '%수익')
            # print('buy :',round(S1_5,5), 'sell :',ohlcv[-day][4])
            count += 1
            temp.append(earning)
        # except:
        #    continue
        # print(item + '에러-------------------------------------------')
        # print ('', end = '', flush = True)
    print("")
    if count != 0:
        return count, sum(temp), sum(temp) * (count / 7)
    else:
        return 0, 0, 0


ticker_list = [
    "ETH/USDT",
    "NEO/USDT",
    "LTC/USDT",
    "QTUM/USDT",
    "ADA/USDT",
    "XRP/USDT",
    "EOS/USDT",
    "IOTA/USDT",
    "XLM/USDT",
    "ONT/USDT",
    "TRX/USDT",
    "ETC/USDT",
    "ICX/USDT",
    "NULS/USDT",
    "VET/USDT",
    "BCH/USDT",
    "LINK/USDT",
    "WAVES/USDT",
    "BTT/USDT",
    "ONG/USDT",
    "HOT/USDT",
    "ZIL/USDT",
    "ZRX/USDT",
    "FET/USDT",
    "BAT/USDT",
    "XMR/USDT",
    "ZEC/USDT",
    "IOST/USDT",
    "CELR/USDT",
    "DASH/USDT",
    "NANO/USDT",
    "OMG/USDT",
    "THETA/USDT",
    "ENJ/USDT",
    "MITH/USDT",
    "MATIC/USDT",
    "ATOM/USDT",
    "TFUEL/USDT",
    "ONE/USDT",
    "FTM/USDT",
    "ALGO/USDT",
    "GTO/USDT",
    "ERD/USDT",
    "DOGE/USDT",
    "DUSK/USDT",
    "ANKR/USDT",
    "WIN/USDT",
    "COS/USDT",
    "NPXS/USDT",
    "COCOS/USDT",
    "MTL/USDT",
    "TOMO/USDT",
    "PERL/USDT",
    "DENT/USDT",
    "MFT/USDT",
    "KEY/USDT",
    "DOCK/USDT",
    "WAN/USDT",
    "FUN/USDT",
    "CVC/USDT",
    "CHZ/USDT",
    "BAND/USDT",
    "BEAM/USDT",
    "XTZ/USDT",
    "REN/USDT",
    "RVN/USDT",
    "HC/USDT",
    "HBAR/USDT",
    "NKN/USDT",
    "STX/USDT",
    "KAVA/USDT",
    "ARPA/USDT",
    "IOTX/USDT",
    "RLC/USDT",
    "MCO/USDT",
    "CTXC/USDT",
    "TROY/USDT",
    "VITE/USDT",
    "FTT/USDT",
    "OGN/USDT",
    "DREP/USDT",
    "TCT/USDT",
    "WRX/USDT",
    "BTS/USDT",
    "LSK/USDT",
    "BNT/USDT",
    "LTO/USDT",
    "STRAT/USDT",
    "AION/USDT",
    "MBL/USDT",
    "COTI/USDT",
    "STPT/USDT",
    "WTC/USDT",
    "DATA/USDT",
    "XZC/USDT",
    "CTSI/USDT",
    "HIVE/USDT",
    "CHR/USDT",
    "BTCUP/USDT",
    "BTCDOWN/USDT",
    "GXS/USDT",
    "ARDR/USDT",
    "LEND/USDT",
    "MDT/USDT",
    "STMX/USDT",
    "KNC/USDT",
    "REP/USDT",
    "LRC/USDT",
    "PNT/USDT",
]

ticker_list = [
    "BTC/USDT",
    "ETH/USDT",
    "BCH/USDT",
    "XRP/USDT",
    "EOS/USDT",
    "LTC/USDT",
    "TRX/USDT",
    "ETC/USDT",
    "LINK/USDT",
    "XLM/USDT",
    "ADA/USDT",
    "XMR/USDT",
    "DASH/USDT",
    "ZEC/USDT",
    "XTZ/USDT",
    "BNB/USDT",
    "ATOM/USDT",
    "ONT/USDT",
    "IOTA/USDT",
    "BAT/USDT",
    "VET/USDT",
    "NEO/USDT",
    "QTUM/USDT",
    "IOST/USDT",
    "THETA/USDT",
    "ALGO/USDT",
    "ZIL/USDT",
    "KNC/USDT",
    "ZRX/USDT",
    "COMP/USDT",
    "OMG/USDT",
    "DOGE/USDT",
    "SXP/USDT",
    "KAVA/USDT",
    "BAND/USDT",
    "RLC/USDT",
    "WAVES/USDT",
    "MKR/USDT",
    "SNX/USDT",
    "DOT/USDT",
    "YFI/USDT",
    "BAL/USDT",
    "CRV/USDT",
    "TRB/USDT",
    "YFII/USDT",
    "RUNE/USDT",
    "SUSHI/USDT",
    "SRM/USDT",
    "BZRX/USDT",
    "EGLD/USDT",
    "SOL/USDT",
    "ICX/USDT",
    "STORJ/USDT",
    "BLZ/USDT",
    "UNI/USDT",
    "AVAX/USDT",
    "FTM/USDT",
    "HNT/USDT",
    "ENJ/USDT",
    "FLM/USDT",
    "TOMO/USDT",
    "REN/USDT",
    "KSM/USDT",
    "NEAR/USDT",
    "AAVE/USDT",
    "FIL/USDT",
    "RSR/USDT",
    "LRC/USDT",
    "MATIC/USDT",
    "OCEAN/USDT",
    "CVC/USDT",
    "BEL/USDT",
    "CTK/USDT",
    "AXS/USDT",
    "ALPHA/USDT",
    "ZEN/USDT",
    "SKL/USDT",
    "GRT/USDT",
    "1INCH/USDT",
    "BTC/BUSD",
    "AKRO/USDT",
    "CHZ/USDT",
    "SAND/USDT",
    "ANKR/USDT",
    "LUNA/USDT",
    "BTS/USDT",
    "LIT/USDT",
    "UNFI/USDT",
    "DODO/USDT",
    "REEF/USDT",
    "RVN/USDT",
    "SFP/USDT",
    "XEM/USDT",
    "COTI/USDT",
    "CHR/USDT",
    "MANA/USDT",
    "ALICE/USDT",
    "HBAR/USDT",
    "ONE/USDT",
    "LINA/USDT",
    "STMX/USDT",
    "DENT/USDT",
    "CELR/USDT",
    "HOT/USDT",
    "MTL/USDT",
    "OGN/USDT",
    "BTT/USDT",
    "NKN/USDT",
    "SC/USDT",
    "DGB/USDT",
    "ICP/USDT",
    "BAKE/USDT",
]

temp_ = [
    "BTC/USDT",
    "BAKE/USDT",
    "XRP/USDT",
    "GBP/USDT",
    "EUR/USDT",
    "AUD/USDT",
    "USDC/USDT",
    "TUSD/USDT",
    "PAX/USDT",
    "BUSD/USDT",
    "FIL/USDT",
    "ADA/USDT",
    "BNB/USDT",
    "TRX/USDT",
    "VET/USDT",
    "ZEC/USDT",
    "THETA/USDT",
    "ETH/USDT",
    "OMG/USDT",
    "DOGE/USDT",
    "ONT/USDT",
    "ETC/USDT",
    "TLM/USDT",
    "EOS/USDT",
    "AKRO/USDT",
    "IOTX/USDT",
    "REEF/USDT",
    "XLM/USDT",
    "DOT/USDT",
    "BTCDOWN/USDT",
    "TRXUP/USDT",
    "BTT/USDT",
    "ENJ/USDT",
    "DASH/USDT",
    "LTC/USDT",
    "UNI/USDT",
    "BCH/USDT",
    "LINK/USDT",
    "CHZ/USDT",
    "SXP/USDT",
    "SUSHI/USDT",
    "FTM/USDT",
    "NEAR/USDT",
    "NKN/USDT",
    "OCEAN/USDT",
    "CRV/USDT",
    "PAXG/USDT",
    "GRT/USDT",
    "MANA/USDT",
    "CAKE/USDT",
    "SOL/USDT",
    "LUNA/USDT",
    "HOT/USDT",
    "1INCH/USDT",
    "ICP/USDT",
    "BAR/USDT",
    "ALGO/USDT",
    "REN/USDT",
    "SHIB/USDT",
    "HARD/USDT",
    "XEM/USDT",
    "COTI/USDT",
    "SNX/USDT",
    "LRC/USDT",
    "NEO/USDT",
    "MATIC/USDT",
    "WAVES/USDT",
    "ATOM/USDT",
    "XTZ/USDT",
    "ONE/USDT",
    "EGLD/USDT",
    "KSM/USDT",
    "SLP/USDT",
    "WRX/USDT",
    "HBAR/USDT",
    "AAVE/USDT",
    "WIN/USDT",
    "ZIL/USDT",
    "ANKR/USDT",
    "XMR/USDT",
    "SRM/USDT",
    "PUNDIX/USDT",
    "MIR/USDT",
    "COMP/USDT",
    "RSR/USDT",
    "AVAX/USDT",
    "MDT/USDT",
    "SKL/USDT",
    "BAT/USDT",
    "STRAX/USDT",
    "RUNE/USDT",
    "QTUM/USDT",
    "FTT/USDT",
    "SFP/USDT",
    "MKR/USDT",
    "IOST/USDT",
    "ETHDOWN/USDT",
    "BAND/USDT",
    "ZRX/USDT",
    "RVN/USDT",
    "ARDR/USDT",
    "YFI/USDT",
    "BZRX/USDT",
    "GTO/USDT",
    "DENT/USDT",
    "STMX/USDT",
    "HNT/USDT",
    "IOTA/USDT",
    "ALPHA/USDT",
    "CTK/USDT",
    "LIT/USDT",
    "ICX/USDT",
    "ROSE/USDT",
    "PNT/USDT",
    "CHR/USDT",
    "SC/USDT",
    "BLZ/USDT",
    "BNT/USDT",
    "DODO/USDT",
    "ETH/BTC",
    "LTC/BTC",
    "XRP/BTC",
    "BNB/BTC",
    "PPT/BTC",
    "MDA/BTC",
    "LINK/BTC",
    "NEO/BTC",
    "LUNA/BTC",
    "OMG/BTC",
    "ICP/BTC",
    "ALGO/BTC",
    "ADA/BTC",
    "CTK/BTC",
    "XLM/BTC",
    "GRT/BTC",
    "QTUM/BTC",
    "MANA/BTC",
    "XTZ/BTC",
    "UTK/BTC",
    "SXP/BTC",
    "NEBL/BTC",
    "UNI/BTC",
    "ZEC/BTC",
    "DOT/BTC",
    "DOGE/BTC",
    "ONT/BTC",
    "EOS/BTC",
    "AVAX/BTC",
    "NAV/BTC",
    "THETA/BTC",
    "CHZ/BTC",
    "HNT/BTC",
    "BAND/BTC",
    "MATIC/BTC",
    "GVT/BTC",
    "ELF/BTC",
    "WABI/BTC",
    "OCEAN/BTC",
    "RUNE/BTC",
    "BCD/BTC",
    "BZRX/BTC",
    "FTT/BTC",
    "SUSHI/BTC",
    "ATOM/BTC",
    "IOTA/BTC",
    "SYS/BTC",
    "LSK/BTC",
    "ETC/BTC",
    "PERP/BTC",
    "BTG/BTC",
    "SNX/BTC",
    "WRX/BTC",
    "NEAR/BTC",
    "ALICE/BTC",
    "KAVA/BTC",
    "RLC/BTC",
    "AUDIO/BTC",
    "FIL/BTC",
    "SCRT/BTC",
    "OAX/BTC",
    "WAVES/BTC",
    "BAT/BTC",
    "ICX/BTC",
    "DNT/BTC",
    "AERGO/BTC",
    "NKN/BTC",
    "BRD/BTC",
    "NANO/BTC",
    "ADX/BTC",
    "KNC/BTC",
    "BAL/BTC",
    "FTM/BTC",
    "GXS/BTC",
    "1INCH/BTC",
    "GAS/BTC",
    "SKY/BTC",
    "ARK/BTC",
    "SOL/BTC",
    "CRV/BTC",
    "ENJ/BTC",
    "ZRX/BTC",
    "SUSD/BTC",
    "CAKE/BTC",
    "EPS/BTC",
    "BNT/BTC",
    "ORN/BTC",
    "INJ/BTC",
    "LTO/BTC",
    "MIR/BTC",
    "BEL/BTC",
    "BQX/BTC",
    "SRM/BTC",
    "DUSK/BTC",
    "COTI/BTC",
    "WAN/BTC",
    "TOMO/BTC",
    "DIA/BTC",
    "OG/BTC",
    "ONE/BTC",
    "SKL/BTC",
    "AGI/BTC",
    "STX/BTC",
    "TFUEL/BTC",
    "STORJ/BTC",
    "TVK/BTC",
    "AION/BTC",
    "HBAR/BTC",
    "FRONT/BTC",
    "UMA/BTC",
    "ANKR/BTC",
    "VITE/BTC",
    "VET/BTC",
    "POLY/BTC",
    "AST/BTC",
    "STEEM/BTC",
    "REN/BTC",
    "CTXC/BTC",
    "VIDT/BTC",
    "CHR/BTC",
    "BNB/ETH",
    "ADA/ETH",
    "PROS/ETH",
    "VET/ETH",
    "EOS/ETH",
    "CDT/ETH",
    "QKC/ETH",
    "PUNDIX/ETH",
    "ZIL/ETH",
    "ELF/ETH",
    "LTC/ETH",
    "LINK/ETH",
    "TRX/ETH",
    "XRP/ETH",
    "ONT/ETH",
    "XLM/ETH",
    "NEO/ETH",
    "ETC/ETH",
    "THETA/ETH",
    "GLM/ETH",
    "AAVE/ETH",
    "BAT/ETH",
    "ENJ/ETH",
    "DEXE/ETH",
    "BNT/ETH",
    "KMD/ETH",
    "HOT/ETH",
    "XVG/ETH",
    "NEBL/ETH",
    "IOTX/ETH",
    "OMG/ETH",
    "NAS/ETH",
    "ZRX/ETH",
    "SCRT/ETH",
    "STMX/ETH",
    "GRT/ETH",
    "NANO/ETH",
    "QTUM/ETH",
    "SLP/ETH",
    "RLC/ETH",
    "SC/ETH",
    "MFT/ETH",
    "TRX/BNB",
    "HBAR/BNB",
    "CAKE/BNB",
    "ZEN/BNB",
    "HOT/BNB",
    "BTT/BNB",
    "DOT/BNB",
    "UNI/BNB",
    "XRP/BNB",
    "LUNA/BNB",
    "VET/BNB",
    "JST/BNB",
    "ADA/BNB",
    "XLM/BNB",
    "EOS/BNB",
    "LTC/BNB",
    "CHZ/BNB",
    "ICP/BNB",
    "XVS/BNB",
    "PROM/BNB",
    "SPARTA/BNB",
    "MATIC/BNB",
    "AVAX/BNB",
    "DGB/BNB",
    "SOL/BNB",
    "RUNE/BNB",
    "CHR/BNB",
    "ETC/BNB",
    "INJ/BNB",
    "BAT/BNB",
    "THETA/BNB",
    "VTHO/BNB",
    "ENJ/BNB",
    "KSM/BNB",
    "COS/BNB",
    "SUSHI/BNB",
    "OGN/BNB",
    "CTSI/BNB",
    "ZIL/BNB",
    "CREAM/BNB",
    "IOST/BNB",
    "NEO/BNB",
    "SRM/BNB",
    "EGLD/BNB",
    "CELR/BNB",
    "BURGER/BNB",
    "STX/BNB",
    "FIL/BNB",
    "BAKE/BNB",
    "FTT/BNB",
    "ONE/BNB",
    "WRX/BNB",
]

ticker_list = [temp_[i] for i in range(len(temp_)) if "/USDT" not in temp_[i]]
# print(ticker_list)

ticker_list = [
    "BTC/USDT",
    "ETH/USDT",
    "BCH/USDT",
    "XRP/USDT",
    "EOS/USDT",
    "LTC/USDT",
    "TRX/USDT",
    "ETC/USDT",
    "LINK/USDT",
    "XLM/USDT",
    "ADA/USDT",
    "XMR/USDT",
    "DASH/USDT",
    "ZEC/USDT",
    "XTZ/USDT",
    "BNB/USDT",
    "ATOM/USDT",
    "ONT/USDT",
    "IOTA/USDT",
    "BAT/USDT",
    "VET/USDT",
    "NEO/USDT",
    "QTUM/USDT",
    "IOST/USDT",
    "THETA/USDT",
    "ALGO/USDT",
    "ZIL/USDT",
    "KNC/USDT",
    "ZRX/USDT",
    "COMP/USDT",
    "OMG/USDT",
    "DOGE/USDT",
    "SXP/USDT",
    "KAVA/USDT",
    "BAND/USDT",
    "RLC/USDT",
    "WAVES/USDT",
    "MKR/USDT",
    "SNX/USDT",
    "DOT/USDT",
    "YFI/USDT",
    "BAL/USDT",
    "CRV/USDT",
    "TRB/USDT",
    "YFII/USDT",
    "RUNE/USDT",
    "SUSHI/USDT",
    "SRM/USDT",
    "BZRX/USDT",
    "EGLD/USDT",
    "SOL/USDT",
    "ICX/USDT",
    "STORJ/USDT",
    "BLZ/USDT",
    "UNI/USDT",
    "AVAX/USDT",
    "FTM/USDT",
    "HNT/USDT",
    "ENJ/USDT",
    "FLM/USDT",
    "TOMO/USDT",
    "REN/USDT",
    "KSM/USDT",
    "NEAR/USDT",
    "AAVE/USDT",
    "FIL/USDT",
    "RSR/USDT",
    "LRC/USDT",
    "MATIC/USDT",
    "OCEAN/USDT",
    "CVC/USDT",
    "BEL/USDT",
    "CTK/USDT",
    "AXS/USDT",
    "ALPHA/USDT",
    "ZEN/USDT",
    "SKL/USDT",
    "GRT/USDT",
    "1INCH/USDT",
    "AKRO/USDT",
    "CHZ/USDT",
    "SAND/USDT",
    "ANKR/USDT",
    "LUNA/USDT",
    "BTS/USDT",
    "LIT/USDT",
    "UNFI/USDT",
    "DODO/USDT",
    "REEF/USDT",
    "RVN/USDT",
    "SFP/USDT",
    "XEM/USDT",
    "COTI/USDT",
    "CHR/USDT",
    "MANA/USDT",
    "ALICE/USDT",
    "HBAR/USDT",
    "ONE/USDT",
    "LINA/USDT",
    "STMX/USDT",
    "DENT/USDT",
    "CELR/USDT",
    "HOT/USDT",
    "MTL/USDT",
    "OGN/USDT",
    "BTT/USDT",
    "NKN/USDT",
    "SC/USDT",
    "DGB/USDT",
    "ICP/USDT",
    "BAKE/USDT",
    "GTC/USDT",
    "KEEP/USDT",
]

ticker_list = [
    "BAKE/USDT",
    "NKN/USDT",
    "XEM/USDT",
    "LRC/USDT",
    "ZEC/USDT",
    "LINA/USDT",
    "YFI/USDT",
    "RVN/USDT",
    "QTUM/USDT",
    "SXP/USDT",
    "CVC/USDT",
    "CHZ/USDT",
    "REEF/USDT",
    "FIL/USDT",
    "MTL/USDT",
    "XRP/USDT",
    "MATIC/USDT",
    "COTI/USDT",
    "NEO/USDT",
    "ALGO/USDT",
    "HBAR/USDT",
    "BAT/USDT",
    "REN/USDT",
    "ADA/USDT",
    "AVAX/USDT",
    "HOT/USDT",
    "TRX/USDT",
    "AXS/USDT",
    "AKRO/USDT",
    "SC/USDT",
    "ALPHA/USDT",
    "KNC/USDT",
    "CHR/USDT",
    "AUDIO/USDT",
    "XTZ/USDT",
    "KSM/USDT",
    "BTS/USDT",
    "HNT/USDT",
    "DASH/USDT",
    "ICP/USDT",
    "DGB/USDT",
    "DOGE/USDT",
    "VET/USDT",
    "AAVE/USDT",
    "IOTX/USDT",
    "SRM/USDT",
    "ONE/USDT",
    "RLC/USDT",
    "NEAR/USDT",
    "GTC/USDT",
    "STORJ/USDT",
    "EGLD/USDT",
    "WAVES/USDT",
    "ETH/USDT",
    "1INCH/USDT",
    "EOS/USDT",
    "LUNA/USDT",
    "UNFI/USDT",
    "SUSHI/USDT",
    "RSR/USDT",
    "OMG/USDT",
    "IOTA/USDT",
    "DODO/USDT",
    "CRV/USDT",
    "ICX/USDT",
    "ALICE/USDT",
    "OGN/USDT",
    "RAY/USDT",
    "BCH/USDT",
    "FTM/USDT",
    "BLZ/USDT",
    "BNB/USDT",
    "KAVA/USDT",
    "SKL/USDT",
    "SOL/USDT",
    "OCEAN/USDT",
    "BTC/USDT",
    "BTCDOM/USDT",
    "LINK/USDT",
    "SAND/USDT",
    "ZRX/USDT",
    "C98/USDT",
    "XLM/USDT",
    "ANKR/USDT",
    "MANA/USDT",
    "TRB/USDT",
    "BTT/USDT",
    "THETA/USDT",
    "UNI/USDT",
    "STMX/USDT",
    "KEEP/USDT",
    "IOST/USDT",
    "BAND/USDT",
    "ETC/USDT",
    "ZIL/USDT",
    "ENJ/USDT",
    "LTC/USDT",
    "BZRX/USDT",
    "RUNE/USDT",
    "CTK/USDT",
    "LIT/USDT",
    "SFP/USDT",
    "ATOM/USDT",
    "ZEN/USDT",
    "TOMO/USDT",
    "YFII/USDT",
    "DEFI/USDT",
    "FLM/USDT",
    "BEL/USDT",
    "COMP/USDT",
    "ONT/USDT",
    "1000SHIB/USDT",
    "TLM/USDT",
    "DOT/USDT",
    "GRT/USDT",
    "XMR/USDT",
    "MKR/USDT",
    "CELR/USDT",
    "BAL/USDT",
    "DENT/USDT",
    "SNX/USDT",
]
# futuers

time_ = datetime.datetime.now()
print(time_)

for i in range(2, 40):
    random.shuffle(ticker_list)
    a, b, c = temp_func(i, 1.98)
    # print('day',i,': ','count =' ,a,'   earining =' , b, '    total = ', c)
    if a == 0:
        continue
    print("day", i, ": ", "count =", a, "   earining =", b, "    avg = ", b / a)

time_ = datetime.datetime.now()
print(time_)
