import ccxt
import time
import os
import numpy as np
import pandas as pd
import datetime
import pandas_ta as ta
import urllib
import json
from all_func import *
import multiprocessing
import parmap


binance = ccxt.binance(
    {
        # "options": {"defaultType": "future"},
        "timeout": 30000,
        "apiKey": "f6LEy0POPdaukqwlrnC4KvJbGWkcXRfVmKbsPmFAaPlyL2Rytswf7ilTa3kAjnQh",
        "secret": "sLvrd7ZT6c49yZVlnFRhPvJcIg8z39S6dVwZcIfPhFueA5BAy5UpTT3ZbVZg9zA2",
        "enableRateLimit": True,
    }
)


def get_target(item):
    try:
        ohlcv_temp = custom_convert(get_ohlcv(item, "5m", 500))
        df = pd.DataFrame(
            data=np.array(ohlcv_temp), columns=["0", "0", "close", "0", "0"]
        )  ## rsi(10, high)
        rsi_entry = df.ta.rsi(length=15).tolist()
        if rsi_entry[-2] < 19 and item not in list(is_entering.keys()):
            return item
    except Exception as e:
        print(e)
        time.sleep(0.1)
    return None


is_entering = {}

if __name__ == "__main__":
    # num_cores = multiprocessing.cpu_count()
    num_cores = 4
    # ticker_list = get_ticker_list()
    ticker_list = [
        "BTC/USDT",
        "BAKE/USDT",
        "XRP/USDT",
        "GBP/USDT",
        "EUR/USDT",
        "AUD/USDT",
        "USDC/USDT",
        "TUSD/USDT",
        "PAX/USDT",
        "BUSD/USDT",
        "FIL/USDT",
        "ADA/USDT",
        "BNB/USDT",
        "TRX/USDT",
        "VET/USDT",
        "ZEC/USDT",
        "THETA/USDT",
        "ETH/USDT",
        "OMG/USDT",
        "DOGE/USDT",
        "ONT/USDT",
        "ETC/USDT",
        "TLM/USDT",
        "EOS/USDT",
        "AKRO/USDT",
        "IOTX/USDT",
        "REEF/USDT",
        "XLM/USDT",
        "DOT/USDT",
        "BTCDOWN/USDT",
        "TRXUP/USDT",
        "BTT/USDT",
        "ENJ/USDT",
        "DASH/USDT",
        "LTC/USDT",
        "UNI/USDT",
        "BCH/USDT",
        "LINK/USDT",
        "CHZ/USDT",
        "SXP/USDT",
        "SUSHI/USDT",
        "FTM/USDT",
        "NEAR/USDT",
        "NKN/USDT",
        "OCEAN/USDT",
        "CRV/USDT",
        "PAXG/USDT",
        "GRT/USDT",
        "MANA/USDT",
        "CAKE/USDT",
        "SOL/USDT",
        "LUNA/USDT",
        "HOT/USDT",
        "1INCH/USDT",
        "ICP/USDT",
        "BAR/USDT",
        "ALGO/USDT",
        "REN/USDT",
        "SHIB/USDT",
        "HARD/USDT",
        "XEM/USDT",
        "COTI/USDT",
        "SNX/USDT",
        "LRC/USDT",
        "NEO/USDT",
        "MATIC/USDT",
        "WAVES/USDT",
        "ATOM/USDT",
        "XTZ/USDT",
        "ONE/USDT",
        "EGLD/USDT",
        "KSM/USDT",
        "SLP/USDT",
        "WRX/USDT",
        "HBAR/USDT",
        "AAVE/USDT",
        "WIN/USDT",
        "ZIL/USDT",
        "ANKR/USDT",
        "XMR/USDT",
        "SRM/USDT",
        "PUNDIX/USDT",
        "MIR/USDT",
        "COMP/USDT",
        "RSR/USDT",
        "AVAX/USDT",
        "MDT/USDT",
        "SKL/USDT",
        "BAT/USDT",
        "STRAX/USDT",
        "RUNE/USDT",
        "QTUM/USDT",
        "FTT/USDT",
        "SFP/USDT",
        "MKR/USDT",
        "IOST/USDT",
        "ETHDOWN/USDT",
        "BAND/USDT",
        "ZRX/USDT",
        "RVN/USDT",
        "ARDR/USDT",
        "YFI/USDT",
        "BZRX/USDT",
        "GTO/USDT",
        "DENT/USDT",
        "STMX/USDT",
        "HNT/USDT",
        "IOTA/USDT",
        "ALPHA/USDT",
        "CTK/USDT",
        "LIT/USDT",
        "ICX/USDT",
        "ROSE/USDT",
        "PNT/USDT",
        "CHR/USDT",
        "SC/USDT",
        "BLZ/USDT",
        "BNT/USDT",
        "DODO/USDT",
        "ETH/BTC",
        "LTC/BTC",
        "XRP/BTC",
        "BNB/BTC",
        "PPT/BTC",
        "MDA/BTC",
        "LINK/BTC",
        "NEO/BTC",
        "LUNA/BTC",
        "OMG/BTC",
        "ICP/BTC",
        "ALGO/BTC",
        "ADA/BTC",
        "CTK/BTC",
        "XLM/BTC",
        "GRT/BTC",
        "QTUM/BTC",
        "MANA/BTC",
        "XTZ/BTC",
        "UTK/BTC",
        "SXP/BTC",
        "NEBL/BTC",
        "UNI/BTC",
        "ZEC/BTC",
        "DOT/BTC",
        "DOGE/BTC",
        "ONT/BTC",
        "EOS/BTC",
        "AVAX/BTC",
        "NAV/BTC",
        "THETA/BTC",
        "CHZ/BTC",
        "HNT/BTC",
        "BAND/BTC",
        "MATIC/BTC",
        "GVT/BTC",
        "ELF/BTC",
        "WABI/BTC",
        "OCEAN/BTC",
        "RUNE/BTC",
        "BCD/BTC",
        "BZRX/BTC",
        "FTT/BTC",
        "SUSHI/BTC",
        "ATOM/BTC",
        "IOTA/BTC",
        "SYS/BTC",
        "LSK/BTC",
        "ETC/BTC",
        "PERP/BTC",
        "BTG/BTC",
        "SNX/BTC",
        "WRX/BTC",
        "NEAR/BTC",
        "ALICE/BTC",
        "KAVA/BTC",
        "RLC/BTC",
        "AUDIO/BTC",
        "FIL/BTC",
        "SCRT/BTC",
        "OAX/BTC",
        "WAVES/BTC",
        "BAT/BTC",
        "ICX/BTC",
        "DNT/BTC",
        "AERGO/BTC",
        "NKN/BTC",
        "BRD/BTC",
        "NANO/BTC",
        "ADX/BTC",
        "KNC/BTC",
        "BAL/BTC",
        "FTM/BTC",
        "GXS/BTC",
        "1INCH/BTC",
        "GAS/BTC",
        "SKY/BTC",
        "ARK/BTC",
        "SOL/BTC",
        "CRV/BTC",
        "ENJ/BTC",
        "ZRX/BTC",
        "SUSD/BTC",
        "CAKE/BTC",
        "EPS/BTC",
        "BNT/BTC",
        "ORN/BTC",
        "INJ/BTC",
        "LTO/BTC",
        "MIR/BTC",
        "BEL/BTC",
        "BQX/BTC",
        "SRM/BTC",
        "DUSK/BTC",
        "COTI/BTC",
        "WAN/BTC",
        "TOMO/BTC",
        "DIA/BTC",
        "OG/BTC",
        "ONE/BTC",
        "SKL/BTC",
        "AGI/BTC",
        "STX/BTC",
        "TFUEL/BTC",
        "STORJ/BTC",
        "TVK/BTC",
        "AION/BTC",
        "HBAR/BTC",
        "FRONT/BTC",
        "UMA/BTC",
        "ANKR/BTC",
        "VITE/BTC",
        "VET/BTC",
        "POLY/BTC",
        "AST/BTC",
        "STEEM/BTC",
        "REN/BTC",
        "CTXC/BTC",
        "VIDT/BTC",
        "CHR/BTC",
        "BNB/ETH",
        "ADA/ETH",
        "PROS/ETH",
        "VET/ETH",
        "EOS/ETH",
        "CDT/ETH",
        "QKC/ETH",
        "PUNDIX/ETH",
        "ZIL/ETH",
        "ELF/ETH",
        "LTC/ETH",
        "LINK/ETH",
        "TRX/ETH",
        "XRP/ETH",
        "ONT/ETH",
        "XLM/ETH",
        "NEO/ETH",
        "ETC/ETH",
        "THETA/ETH",
        "GLM/ETH",
        "AAVE/ETH",
        "BAT/ETH",
        "ENJ/ETH",
        "DEXE/ETH",
        "BNT/ETH",
        "KMD/ETH",
        "HOT/ETH",
        "XVG/ETH",
        "NEBL/ETH",
        "IOTX/ETH",
        "OMG/ETH",
        "NAS/ETH",
        "ZRX/ETH",
        "SCRT/ETH",
        "STMX/ETH",
        "GRT/ETH",
        "NANO/ETH",
        "QTUM/ETH",
        "SLP/ETH",
        "RLC/ETH",
        "SC/ETH",
        "MFT/ETH",
        "TRX/BNB",
        "HBAR/BNB",
        "CAKE/BNB",
        "ZEN/BNB",
        "HOT/BNB",
        "BTT/BNB",
        "DOT/BNB",
        "UNI/BNB",
        "XRP/BNB",
        "LUNA/BNB",
        "VET/BNB",
        "JST/BNB",
        "ADA/BNB",
        "XLM/BNB",
        "EOS/BNB",
        "LTC/BNB",
        "CHZ/BNB",
        "ICP/BNB",
        "XVS/BNB",
        "PROM/BNB",
        "SPARTA/BNB",
        "MATIC/BNB",
        "AVAX/BNB",
        "DGB/BNB",
        "SOL/BNB",
        "RUNE/BNB",
        "CHR/BNB",
        "ETC/BNB",
        "INJ/BNB",
        "BAT/BNB",
        "THETA/BNB",
        "VTHO/BNB",
        "ENJ/BNB",
        "KSM/BNB",
        "COS/BNB",
        "SUSHI/BNB",
        "OGN/BNB",
        "CTSI/BNB",
        "ZIL/BNB",
        "CREAM/BNB",
        "IOST/BNB",
        "NEO/BNB",
        "SRM/BNB",
        "EGLD/BNB",
        "CELR/BNB",
        "BURGER/BNB",
        "STX/BNB",
        "FIL/BNB",
        "BAKE/BNB",
        "FTT/BNB",
        "ONE/BNB",
        "WRX/BNB",
    ]

    result = parmap.map(get_target, ticker_list, pm_pbar=True, pm_processes=num_cores)
    result = list(set(result) - set([None]))
    print(result)
